'use server';
/**
 * @fileOverview AI-powered portfolio item tagger.
 *
 * - aiTagPortfolioItems - A function that adds AI generated tags to portfolio items.
 * - AITagPortfolioItemsInput - The input type for the aiTagPortfolioItems function.
 * - AITagPortfolioItemsOutput - The return type for the aiTagPortfolioItems function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const AITagPortfolioItemsInputSchema = z.object({
  itemDescription: z.string().describe('A description of the portfolio item.'),
  itemTitle: z.string().describe('The title of the portfolio item.'),
});
export type AITagPortfolioItemsInput = z.infer<typeof AITagPortfolioItemsInputSchema>;

const AITagPortfolioItemsOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of tags generated by AI for the portfolio item.'),
});
export type AITagPortfolioItemsOutput = z.infer<typeof AITagPortfolioItemsOutputSchema>;

export async function aiTagPortfolioItems(input: AITagPortfolioItemsInput): Promise<AITagPortfolioItemsOutput> {
  return aiTagPortfolioItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiTagPortfolioItemsPrompt',
  input: {schema: AITagPortfolioItemsInputSchema},
  output: {schema: AITagPortfolioItemsOutputSchema},
  prompt: `You are an expert at generating SEO-friendly tags for portfolio items. Based on the description and title provided, generate an array of 5 to 7 relevant tags that can be used to categorize the portfolio item and improve its discoverability.

Title: {{{itemTitle}}}
Description: {{{itemDescription}}}

Tags:`,
});

const aiTagPortfolioItemsFlow = ai.defineFlow(
  {
    name: 'aiTagPortfolioItemsFlow',
    inputSchema: AITagPortfolioItemsInputSchema,
    outputSchema: AITagPortfolioItemsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
