import type { AppItem, Language } from './types';

export const appsData: Record<Language, AppItem[]> = {
  fr: [
    {
      id: "calcostpro",
      title: "CalCostPro",
      badge: {
        label: "Démo Live",
        dotColor: "bg-emerald-400",
      },
      subtitle: "SaaS IA de calcul de coûts et optimisation de marges pour la confection textile",
      description: "CalCostPro est une application SaaS complète développée pour l'industrie de la confection et du textile. Elle permet de modéliser avec précision le coût de revient unitaire (matières premières, temps d'ouvrier, accessoires, perte) et d'exploiter l'intelligence artificielle pour optimiser les marges et standardiser la politique tarifaire des ateliers.",
      challenge: "Fournir aux confectionneurs un outil rapide, fiable et moderne pour calculer le prix de revient de vêtements complexes sans dépendre de tableurs manuels opaques et sujets aux erreurs.",
      solution: "Création d'une plateforme Full-Stack réactive couplée à des modèles d'IA (Gemini). L'application calcule automatiquement les coûts directs et indirects, détecte les anomalies de prix et propose des simulations de rentabilité dynamiques.",
      features: [
        "Calcul automatisé des coûts de confection et consommations matières",
        "Simulateur prédictif de marges et prix de vente recommandés",
        "Assistance IA pour l'analyse de rentabilité et détection d'écarts",
        "Génération de devis détaillés et exports fiches techniques",
        "Gestion multi-ateliers, fiches produits et historique de tarification",
      ],
      techStack: ["Next.js", "Firebase", "Gemini AI API", "TypeScript", "Tailwind CSS"],
      sliderImage: "/categories/imag1.jpg",
      image: "/portfolio/p9-1.jpg",
      videoUrl: "/video/videoia.mp4",
      gallery: ["/portfolio/p9-1.jpg", "/portfolio/p9-2.jpg", "/portfolio/p9-3.jpg", "/portfolio/p9-4.jpg"],
      liveUrl: "https://calcostpro.com",
      liveUrlLabel: "Lancer calcostpro.com",
      confidential: false,
    },
    {
      id: "mt5-tracker",
      title: "MT5 Pulse",
      badge: {
        label: "Application Locale",
        dotColor: "bg-cyan-400",
      },
      subtitle: "Assistant trading, veille de marché en direct & scalping connecté à MetaTrader 5",
      description: "MT5 Pulse est un assistant de trading professionnel développé en local et connecté directement à MetaTrader 5 (MT5). L'application assure une veille de marché multi-actifs en continu (Forex, Énergies, Indices), détecte automatiquement les opportunités de scalping (M5) et fournit un tableau de bord complet avec suivi des ordres, alertes Telegram et widget de bureau.",
      challenge: "Détecter en temps réel les mouvements directionnels à forte probabilité et surveiller l'exposition du compte sans dépendre de l'interface austère de MetaTrader.",
      solution: "Passerelle locale haute performance avec MetaTrader 5, scanner automatique M5, calcul de ratios Risque/Rendement et diffusion d'alertes instantanées.",
      features: [
        "Connexion temps réel directe à MetaTrader 5 (MT5)",
        "Scanner d'opportunités de scalping M5 avec calcul de Risk/Reward et seuils d'entrée",
        "Veille quotidienne de marché avec détection des tendances globales et envoi Telegram",
        "Dashboard de performance en direct : solde, équité, marge et suivi des positions ouvertes",
        "Widget de bureau dédié pour garder un œil sur les trades sans encombrer l'écran",
      ],
      techStack: ["MetaTrader 5 API", "Python / WebSockets", "Next.js", "Tailwind CSS", "Real-time Algo"],
      sliderImage: "/categories/imag2.jpg",
      image: "/portfolio/mt5-pulse.png",
      gallery: ["/portfolio/mt5-pulse.png"],
      confidential: true,
      confidentialNotice: "Application locale de trading algorithmique et veille de marché (exécutée uniquement sur machine locale pour l'instant).",
    },
    {
      id: "mafamille",
      title: "MA FAMILLE",
      badge: {
        label: "Restaurant & Démo",
        dotColor: "bg-emerald-400",
      },
      subtitle: "Menú & Carte digitale interactive pour crêperie artisanale & café à Cochabamba",
      description: "Développée pour la crêperie artisanale et café MA FAMILLE à Cochabamba (Bolivie), cette application web interactive offre une carte digitale fluide et gourmande. Les clients découvrent en direct les crêpes salées et sucrées, boissons fraîches, options de personnalisation et promotions via QR code sur table ou sur smartphone, avec un système de fidélité intégré.",
      challenge: "Offrir aux clients du restaurant une carte digitale ultra-rapide, appétissante et intuitive sans téléchargement d'application, tout en facilitant la mise à jour des prix, des stocks et des suggestions du chef.",
      solution: "Application web progressive (PWA) optimisée pour mobile avec navigation par catégories (crêpes salées, sucrées, boissons), fiches produits détaillées avec visuels gourmands, système de fidélité numérique avec tampons ('sellos') et générateur de QR codes par table.",
      features: [
        "Menu digital complet : crêpes artisanales salées & sucrées, boissons fraîches et formules",
        "Consultation instantanée sans installation via QR code scannable sur chaque table",
        "Programme de fidélité numérique interactif avec tampons ('sellos') et crêpes offertes",
        "Générateur et téléchargement de QR codes personnalisés par table et supports print",
        "Interface mobile-first réactive, rapide et adaptée aux connexions mobiles",
      ],
      techStack: ["React / Vite", "TypeScript", "Tailwind CSS", "QR Code Engine", "PWA Mobile-First"],
      sliderImage: "/categories/imag3.jpg",
      image: "/portfolio/mafamille-logo.png",
      videoUrl: "/video/mafamille-menu.mp4",
      gallery: [
        "/portfolio/mafamille-logo.png",
        "/portfolio/mafamille-crepe-chocolat.jpg",
        "/portfolio/mafamille-crepe-salee.jpg",
        "/portfolio/mafamille-crepe-nutella.jpg",
      ],
      liveUrl: "https://mafamille.iung.li",
      liveUrlLabel: "Consulter mafamille.iung.li",
      confidential: false,
    },
    {
      id: "impotbo",
      title: "ImpuestosBO",
      badge: {
        label: "Plateforme Fiscale",
        dotColor: "bg-emerald-400",
      },
      subtitle: "Calculateur RC-IVA, décompte Formulaire 110 & portail collaboratif comptable en Bolivie",
      description: "ImpuestosBO est une application web progressive dédiée à la simplification et l'optimisation des obligations fiscales en Bolivie. Elle automatise le calcul du RC-IVA (13%), le crédit d'impôt fixe (2×SMN) et le report de solde antérieur. L'outil intègre un scanner QR de factures d'achat, la génération instantanée du Formulario 110, ainsi qu'un espace collaboratif partagé entre le salarié et son expert-comptable.",
      challenge: "Supprimer la lourdeur et les erreurs manuelles du calcul du RC-IVA et du remplissage du Formulario 110 pour les salariés et les indépendants en Bolivie.",
      solution: "Moteur fiscal automatisé pas à pas : saisie ou scan QR des factures, calcul en direct du solde en faveur du contribuable, et console multi-clients pour les cabinets comptables.",
      features: [
        "Tableau de bord de situation mensuelle RC-IVA avec calcul en direct du solde à payer ou à reporter",
        "Module Formulaire 110 avec décompte automatique : AFP, base imposable, crédit fixe et solde en faveur",
        "Enregistrement rapide de factures avec scanner QR, détection du NIT, CUF et montant déductible",
        "Espace de collaboration avec invitation et délégation d'accès sécurisé à son expert-comptable",
        "Console multi-clients dédiée aux comptables avec suivi centralisé des déclarations fiscales",
      ],
      techStack: ["Next.js / PWA", "TypeScript", "QR Scanner", "Fiscal Rules Engine", "Tailwind CSS"],
      sliderImage: "/categories/imag4.jpg",
      image: "/portfolio/impuestosbo-home.png",
      gallery: [
        "/portfolio/impuestosbo-home.png",
        "/portfolio/impuestosbo-form110.png",
        "/portfolio/impuestosbo-factura.png",
        "/portfolio/impuestosbo-clientes.png",
        "/portfolio/impuestosbo-contador.png",
      ],
      liveUrl: "https://impuestos.iung.li",
      liveUrlLabel: "Accéder à impuestos.iung.li",
      confidential: false,
    },
    {
      id: "secutiquipaya",
      title: "SecuTiquipaya",
      badge: {
        label: "Plateforme Démo",
        dotColor: "bg-purple-400",
      },
      subtitle: "Système citoyen d'alerte SOS & console de commandement Guardia Municipal de Tiquipaya",
      description: "SecuTiquipaya est un écosystème de sécurité publique combinant une PWA citoyenne et une console de supervision en direct pour la Guardia Municipal. Les résidents peuvent déclencher instantanément une alerte SOS géolocalisée (maintien 2s) et consulter les avis de prévention, tandis que les forces d'intervention coordonnent les patrouilles sur carte interactive avec prise en charge temps réel.",
      challenge: "Remplacer les canaux d'alerte informels par une chaîne de secours réactive liant directement les citoyens et le centre de commandement municipal.",
      solution: "Double interface : PWA citoyenne avec déclencheur SOS ultra-rapide et console de supervision Guardia Municipal avec cartographie Leaflet en temps réel et suivi des patrouilles.",
      features: [
        "Application citoyenne PWA avec bouton SOS d'urgence (maintien 2s) et fil d'actualités",
        "Console de commandement Guardia Municipal avec vue SOS Live et carte interactive en direct",
        "Cartographie dynamique (Leaflet / CARTO) avec géolocalisation précise des alertes",
        "Gestion des urgences actives : statut en cours/résolu et notes de patrouille en temps réel",
        "Diffusion d'alertes communautaires et analyse préventive par cartographie",
      ],
      techStack: ["PWA", "Leaflet Maps API", "Firebase Realtime", "Next.js", "Tailwind CSS"],
      sliderImage: "/categories/imag5.jpg",
      image: "/portfolio/secutiquipaya-console.png",
      gallery: ["/portfolio/secutiquipaya-console.png", "/portfolio/secutiquipaya-mobile.png"],
      liveUrl: "http://secutiquipaya.iung.li",
      liveUrlLabel: "Accéder à secutiquipaya.iung.li",
      confidential: false,
    },
  ],
  en: [
    {
      id: "calcostpro",
      title: "CalCostPro",
      badge: {
        label: "Live Demo",
        dotColor: "bg-emerald-400",
      },
      subtitle: "AI SaaS for production cost calculation and margin optimization in the apparel industry",
      description: "CalCostPro is a comprehensive SaaS platform built for the apparel and garment manufacturing sector. It accurately computes unit cost breakdown (fabrics, labor time, trims, waste) and leverages artificial intelligence to recommend optimal pricing scenarios.",
      challenge: "Provide apparel manufacturers with an agile, reliable tool to price complex productions without relying on error-prone manual spreadsheets.",
      solution: "Full-Stack reactive application integrated with Google Gemini AI models to analyze cost structures, highlight discrepancies, and project profit margins.",
      features: [
        "Automated garment production cost & fabric consumption calculation",
        "Predictive margin simulator and recommended selling price engine",
        "AI assistant for profitability review and cost anomaly detection",
        "Quotation generator and detailed tech-pack export",
        "Multi-workshop management, product catalog and price history",
      ],
      techStack: ["Next.js", "Firebase", "Gemini AI API", "TypeScript", "Tailwind CSS"],
      sliderImage: "/categories/imag1.jpg",
      image: "/portfolio/p9-1.jpg",
      videoUrl: "/video/videoia.mp4",
      gallery: ["/portfolio/p9-1.jpg", "/portfolio/p9-2.jpg", "/portfolio/p9-3.jpg", "/portfolio/p9-4.jpg"],
      liveUrl: "https://calcostpro.com",
      liveUrlLabel: "Launch calcostpro.com",
      confidential: false,
    },
    {
      id: "mt5-tracker",
      title: "MT5 Pulse",
      badge: {
        label: "Local Application",
        dotColor: "bg-cyan-400",
      },
      subtitle: "Trading assistant, live multi-market watch & scalping scanner connected to MetaTrader 5",
      description: "MT5 Pulse is a professional desktop/local trading assistant directly connected to MetaTrader 5 (MT5). It continuously monitors multiple asset classes (Forex, Clean Energies, Global Indices), automatically scans for high-probability M5 scalping setups, and provides a real-time account cockpit with Telegram broadcast alerts and a dedicated desktop widget.",
      challenge: "Identify high-probability intraday scalping setups and track account exposure in real time without being tethered to MetaTrader's native legacy UI.",
      solution: "Ultra-fast local bridge with MetaTrader 5, automated M5 scanner, automated Risk/Reward computation, and instant push alerts.",
      features: [
        "Direct real-time bridge to MetaTrader 5 (MT5)",
        "M5 scalping scanner with automated Risk/Reward ratios and entry/SL/TP levels",
        "Daily market trend watch across Green Energies & Indices with Telegram digest",
        "Live performance cockpit: balance, equity, margin and active position tracking",
        "Dedicated desktop widget for ambient monitoring without cluttering screens",
      ],
      techStack: ["MetaTrader 5 API", "Python / WebSockets", "Next.js", "Tailwind CSS", "Real-time Algo"],
      sliderImage: "/categories/imag2.jpg",
      image: "/portfolio/mt5-pulse.png",
      gallery: ["/portfolio/mt5-pulse.png"],
      confidential: true,
      confidentialNotice: "Local algorithmic trading & market surveillance application (currently running in private local environment).",
    },
    {
      id: "mafamille",
      title: "MA FAMILLE",
      badge: {
        label: "Restaurant & Demo",
        dotColor: "bg-emerald-400",
      },
      subtitle: "Interactive digital menu & dining app for artisanal crêperie & café in Cochabamba",
      description: "Developed for the artisanal crêperie and coffee shop MA FAMILLE in Cochabamba (Bolivia), this web application provides a responsive digital menu. Guests can instantly explore sweet and savory gourmet crêpes, fresh beverages, combos, and daily specials via table QR codes or mobile browsers, featuring an integrated digital loyalty program.",
      challenge: "Deliver an appetizing, ultra-fast digital menu requiring zero app installation, while simplifying price updates, seasonal specials, and dish availability.",
      solution: "Mobile-first Progressive Web App (PWA) featuring intuitive category filtering (savory, sweet, drinks), vibrant product visuals, digital stamp card loyalty system, and custom table QR code generation.",
      features: [
        "Full interactive digital menu: artisanal savory & sweet crêpes, drinks and specials",
        "Zero-install instant access via scanned QR codes on restaurant tables",
        "Digital stamp loyalty card rewarding customers with free crêpes and treats",
        "QR code generator and export for tabletop stands and promotional flyers",
        "Ultra-lightweight mobile-first UI optimized for seamless smartphone browsing",
      ],
      techStack: ["React / Vite", "TypeScript", "Tailwind CSS", "QR Code Engine", "PWA Mobile-First"],
      sliderImage: "/categories/imag3.jpg",
      image: "/portfolio/mafamille-logo.png",
      videoUrl: "/video/mafamille-menu.mp4",
      gallery: [
        "/portfolio/mafamille-logo.png",
        "/portfolio/mafamille-crepe-chocolat.jpg",
        "/portfolio/mafamille-crepe-salee.jpg",
        "/portfolio/mafamille-crepe-nutella.jpg",
      ],
      liveUrl: "https://mafamille.iung.li",
      liveUrlLabel: "Visit mafamille.iung.li",
      confidential: false,
    },
    {
      id: "impotbo",
      title: "ImpuestosBO",
      badge: {
        label: "Tax Web App",
        dotColor: "bg-emerald-400",
      },
      subtitle: "RC-IVA tax calculator, Formulario 110 generator & accountant collaboration portal for Bolivia",
      description: "ImpuestosBO is a specialized tax management web application built for the Bolivian fiscal system. It automates RC-IVA calculations, fixed tax credits (2× minimum wage), and prior-month balance carryovers. It includes a QR invoice scanner for deduction credits, automated Formulario 110 preparation, and a multi-client portal for accounting firms.",
      challenge: "Eliminate manual errors and tedious paperwork when preparing RC-IVA withholdings and Formulario 110 filings.",
      solution: "Automated step-by-step fiscal engine: instant QR invoice capture, live favorable tax balance computation, and dedicated accountant client management console.",
      features: [
        "Real-time monthly RC-IVA cockpit calculating payable taxes or favorable balances to carry over",
        "Automated Formulario 110 breakdown: net salary post-AFP, tax base, fixed credit, and invoice deductions",
        "Fast invoice entry with QR scanner, automated NIT/CUF detection, and expense credit validation",
        "Client-to-accountant invitation portal with secure permission management",
        "Multi-client accountant workspace tracking active tax periods and filing deadlines",
      ],
      techStack: ["Next.js / PWA", "TypeScript", "QR Scanner", "Fiscal Rules Engine", "Tailwind CSS"],
      sliderImage: "/categories/imag4.jpg",
      image: "/portfolio/impuestosbo-home.png",
      gallery: [
        "/portfolio/impuestosbo-home.png",
        "/portfolio/impuestosbo-form110.png",
        "/portfolio/impuestosbo-factura.png",
        "/portfolio/impuestosbo-clientes.png",
        "/portfolio/impuestosbo-contador.png",
      ],
      liveUrl: "https://impuestos.iung.li",
      liveUrlLabel: "Visit impuestos.iung.li",
      confidential: false,
    },
    {
      id: "secutiquipaya",
      title: "SecuTiquipaya",
      badge: {
        label: "Demo Platform",
        dotColor: "bg-purple-400",
      },
      subtitle: "Citizen SOS alert app & Guardia Municipal command console for Tiquipaya",
      description: "SecuTiquipaya is a civic public safety ecosystem uniting a mobile citizen PWA and a live dispatch console for the Municipal Guard. Residents can trigger geotagged SOS emergencies (2s hold) and follow prevention bulletins, while dispatchers monitor active incidents on a live map with patrol response tracking.",
      challenge: "Replace disorganized chat channels with an actionable emergency pipeline linking citizens directly to municipal dispatchers.",
      solution: "Dual-interface platform: mobile citizen PWA with instant SOS panic triggers and Municipal Guard command console with live Leaflet mapping and patrol notes.",
      features: [
        "Mobile citizen PWA with emergency SOS button (2-second hold) and prevention bulletins",
        "Guardia Municipal command center with live SOS feed and interactive dispatch map",
        "Dynamic GIS mapping (Leaflet / CARTO) with precise incident coordinates and status pins",
        "Active incident management: dispatch notes, in-progress tracking, and resolution logs",
        "Public alert broadcast system and safety heatmap analytics",
      ],
      techStack: ["PWA", "Leaflet Maps API", "Firebase Realtime", "Next.js", "Tailwind CSS"],
      sliderImage: "/categories/imag5.jpg",
      image: "/portfolio/secutiquipaya-console.png",
      gallery: ["/portfolio/secutiquipaya-console.png", "/portfolio/secutiquipaya-mobile.png"],
      liveUrl: "http://secutiquipaya.iung.li",
      liveUrlLabel: "Visit secutiquipaya.iung.li",
      confidential: false,
    },
  ],
  es: [
    {
      id: "calcostpro",
      title: "CalCostPro",
      badge: {
        label: "Demo en Vivo",
        dotColor: "bg-emerald-400",
      },
      subtitle: "SaaS con IA para el cálculo de costos y optimización de márgenes en confección textil",
      description: "CalCostPro es una plataforma SaaS completa desarrollada para la industria de la confección y la moda. Permite modelar con precisión el costo unitario de producción (materiales, mano de obra, insumos, merma) y utiliza inteligencia artificial para sugerir precios y optimizar márgenes.",
      challenge: "Brindar a los confeccionistas una herramienta rápida y precisa para cotizar producciones complejas sin depender de planillas de cálculo manuales.",
      solution: "Aplicación Full-Stack reactiva combinada con modelos de IA (Gemini). Calcula automáticamente costos directos e indirectos y genera simulaciones de rentabilidad instantáneas.",
      features: [
        "Cálculo automatizado de costos de confección y consumo de telas",
        "Simulador predictivo de márgenes y precios de venta sugeridos",
        "Asistente de IA para análisis de rentabilidad y detección de desvíos",
        "Generación de cotizaciones y fichas técnicas exportables",
        "Gestión multi-talleres, catálogo de prendas e historial de precios",
      ],
      techStack: ["Next.js", "Firebase", "Gemini AI API", "TypeScript", "Tailwind CSS"],
      sliderImage: "/categories/imag1.jpg",
      image: "/portfolio/p9-1.jpg",
      videoUrl: "/video/videoia.mp4",
      gallery: ["/portfolio/p9-1.jpg", "/portfolio/p9-2.jpg", "/portfolio/p9-3.jpg", "/portfolio/p9-4.jpg"],
      liveUrl: "https://calcostpro.com",
      liveUrlLabel: "Abrir calcostpro.com",
      confidential: false,
    },
    {
      id: "mt5-tracker",
      title: "MT5 Pulse",
      badge: {
        label: "Aplicación Local",
        dotColor: "bg-cyan-400",
      },
      subtitle: "Asistente de trading, vigilancia de mercado en vivo y scalping conectado a MetaTrader 5",
      description: "MT5 Pulse es un asistente de trading profesional desarrollado en local y conectado directamente a MetaTrader 5 (MT5). Monitorea continuamente múltiples activos (Forex, Energías Limpias, Índices), detecta automáticamente oportunidades de scalping M5 y ofrece un panel completo con alertas vía Telegram y widget de escritorio.",
      challenge: "Detectar en tiempo real movimientos de alta probabilidad y monitorear la exposición de la cuenta sin depender de la interfaz nativa de MetaTrader.",
      solution: "Puente local de alto rendimiento con MetaTrader 5, escáner automático M5, cálculo instantáneo de ratios Riesgo/Beneficio y alertas en tiempo real.",
      features: [
        "Conexión directa en tiempo real con MetaTrader 5 (MT5)",
        "Escáner de oportunidades de scalping M5 con cálculo de Risk/Reward y niveles de entrada/SL/TP",
        "Vigilancia diaria de tendencias de mercado (Energías Verdes, Índices) y envío a Telegram",
        "Panel en vivo: saldo, equidad, margen libre y seguimiento de posiciones activas",
        "Widget de escritorio exclusivo para supervisión discreta sin saturar la pantalla",
      ],
      techStack: ["MetaTrader 5 API", "Python / WebSockets", "Next.js", "Tailwind CSS", "Real-time Algo"],
      sliderImage: "/categories/imag2.jpg",
      image: "/portfolio/mt5-pulse.png",
      gallery: ["/portfolio/mt5-pulse.png"],
      confidential: true,
      confidentialNotice: "Aplicación local de trading algorítmico y vigilancia de mercado (actualmente ejecutada en entorno local privado).",
    },
    {
      id: "mafamille",
      title: "MA FAMILLE",
      badge: {
        label: "Restaurante & Demo",
        dotColor: "bg-emerald-400",
      },
      subtitle: "Menú y carta digital interactiva para crêperie artesanal y café en Cochabamba",
      description: "Desarrollada para la crêperie artesanal y café MA FAMILLE en Cochabamba (Bolivia), esta aplicación web brinda una carta digital ágil y atractiva. Los clientes descubren crêpes dulces y saladas, bebidas frescas y promociones escaneando el código QR de su mesa o desde cualquier smartphone, con sistema de fidelidad integrado.",
      challenge: "Ofrecer a los comensales una carta digital instantánea, visual y apetitosa sin descargas obligatorias, facilitando al local la actualización de precios y especialidades.",
      solution: "PWA optimizada para móviles con navegación fluida por categorías (saladas, dulces, bebidas), fichas de productos con fotos reales, tarjeta digital de sellos de fidelidad y generación de QR por mesa.",
      features: [
        "Menú digital completo: crêpes gourmet saladas y dulces, bebidas artesanales y combos",
        "Acceso instantáneo sin descargas mediante escaneo de código QR en mesa",
        "Programa de fidelidad digital con acumulación de sellos y crêpes gratis de regalo",
        "Descarga y generación de códigos QR personalizados para mesas y cartelería",
        "Experiencia visual móvil de alto rendimiento y bajo consumo de datos",
      ],
      techStack: ["React / Vite", "TypeScript", "Tailwind CSS", "QR Code Engine", "PWA Mobile-First"],
      sliderImage: "/categories/imag3.jpg",
      image: "/portfolio/mafamille-logo.png",
      videoUrl: "/video/mafamille-menu.mp4",
      gallery: [
        "/portfolio/mafamille-logo.png",
        "/portfolio/mafamille-crepe-chocolat.jpg",
        "/portfolio/mafamille-crepe-salee.jpg",
        "/portfolio/mafamille-crepe-nutella.jpg",
      ],
      liveUrl: "https://mafamille.iung.li",
      liveUrlLabel: "Abrir mafamille.iung.li",
      confidential: false,
    },
    {
      id: "impotbo",
      title: "ImpuestosBO",
      badge: {
        label: "Plataforma Tributaria",
        dotColor: "bg-emerald-400",
      },
      subtitle: "Calculadora RC-IVA, generador de Formulario 110 y portal colaborativo contable en Bolivia",
      description: "ImpuestosBO es una aplicación web especializada en la simplificación y gestión tributaria en Bolivia. Automatiza el cálculo del RC-IVA (13%), el cómputo de crédito fiscal fijo (2×SMN) y el arrastre de saldos. Incluye escáner QR de facturas, generación automática del Formulario 110 y una plataforma colaborativa para contadores y clientes.",
      challenge: "Eliminar errores manuales y demoras en el cálculo del RC-IVA y confección del Formulario 110.",
      solution: "Motor fiscal paso a paso: captura rápida por escáner QR de facturas, cálculo en vivo de saldo a favor o retención, y panel de control multi-cliente para contadores.",
      features: [
        "Panel mensual de situación RC-IVA con saldo a favor o impuesto determinado en tiempo real",
        "Módulo Formulario 110: desglose automático de salario neto, base imponible y créditos de ley",
        "Registro ágil de facturas con escáner QR, detección de NIT, CUF e importe fiscal",
        "Invitación y vinculación segura con contadores de confianza",
        "Consola multi-clientes para despachos contables con control centralizado de declaraciones",
      ],
      techStack: ["Next.js / PWA", "TypeScript", "QR Scanner", "Fiscal Rules Engine", "Tailwind CSS"],
      sliderImage: "/categories/imag4.jpg",
      image: "/portfolio/impuestosbo-home.png",
      gallery: [
        "/portfolio/impuestosbo-home.png",
        "/portfolio/impuestosbo-form110.png",
        "/portfolio/impuestosbo-factura.png",
        "/portfolio/impuestosbo-clientes.png",
        "/portfolio/impuestosbo-contador.png",
      ],
      liveUrl: "https://impuestos.iung.li",
      liveUrlLabel: "Abrir impuestos.iung.li",
      confidential: false,
    },
    {
      id: "secutiquipaya",
      title: "SecuTiquipaya",
      badge: {
        label: "Plataforma Demo",
        dotColor: "bg-purple-400",
      },
      subtitle: "App ciudadana de alerta SOS y consola de mando de la Guardia Municipal de Tiquipaya",
      description: "SecuTiquipaya es un ecosistema de seguridad ciudadana que combina una PWA para vecinos y una consola de supervisión en tiempo real para la Guardia Municipal. Los ciudadanos pueden activar una alarma SOS geolocalizada (manteniendo presionado 2 segundos) y recibir noticias de prevención, mientras la guardia coordina patrullas sobre un mapa en vivo.",
      challenge: "Reemplazar los grupos de mensajería dispersos por un canal estructurado de respuesta rápida entre vecinos y centro de mando municipal.",
      solution: "Doble interfaz: app móvil PWA con botón SOS de emergencia y consola de comando con cartografía Leaflet en tiempo real y registro de patrullas.",
      features: [
        "Aplicación ciudadana PWA con botón SOS de emergencia (2 seg) y noticias de prevención",
        "Consola de mando Guardia Municipal con monitor SOS en vivo y mapa interactivo",
        "Cartografía en tiempo real (Leaflet / CARTO) con localización precisa de alertas",
        "Gestión de urgencias activas: notas de seguimiento de patrulla y resolución de alertas",
        "Canal de difusión comunitaria y visualización de análisis preventivo",
      ],
      techStack: ["PWA", "Leaflet Maps API", "Firebase Realtime", "Next.js", "Tailwind CSS"],
      sliderImage: "/categories/imag5.jpg",
      image: "/portfolio/secutiquipaya-console.png",
      gallery: ["/portfolio/secutiquipaya-console.png", "/portfolio/secutiquipaya-mobile.png"],
      liveUrl: "http://secutiquipaya.iung.li",
      liveUrlLabel: "Abrir secutiquipaya.iung.li",
      confidential: false,
    },
  ],
};
