import type { Translations } from './types';
import { portfolioItems } from './portfolio-data';

export const translations: Translations = {
  fr: {
    aboutNav: 'À propos',
    portfolioNav: 'Portfolio',
    contactNav: 'Contact',
    aiLabNav: 'IA & Conseil',
    heroTitle: 'Emmanuel Iung',
    heroSubtitle: 'Designer graphique, Développeur Web et passionné d\'IA avec plus de 20 ans d\'expérience. Je transforme les idées en expériences visuelles captivantes.',
    heroCta: 'Découvrir mon travail',
    aboutTitle: 'De la conception graphique à la création d\'applications IA',
    aboutParagraph1: 'Je suis Emmanuel Iung. Avec plus de deux décennies d\'expérience en design graphique, j\'ai cultivé une passion pour l\'esthétique visuelle et une communication claire. Mon parcours a commencé avec les outils traditionnels, mais ma curiosité m\'a rapidement poussé vers le numérique. J\'ai adopté WordPress à ses débuts, développant des sites web qui alliaient fonctionnalité et design.',
    aboutParagraph2: 'Aujourd\'hui, je suis à la pointe de l\'innovation, en intégrant l\'intelligence artificielle dans mes créations. J\'utilise les outils de Google Cloud pour construire des applications intelligentes et collaboratives. Mon objectif est de fusionner mon expertise en design avec la puissance de l\'IA pour créer des solutions uniques et percutantes.',
    portfolioTitle: 'Mes Projets',
    portfolioFilterAll: 'Tous',
    portfolioFilterDesign: 'Design Graphique',
    portfolioFilterDev: 'Développement Web',
    portfolioFilterAi: 'Projets IA',
    portfolioAiNotice: 'Générateur de Tags IA',
    
    aiLabTitle: 'Transformer vos idées en outils IA concrets',
    aiLabIntro: "Mon profil unique de designer et développeur me permet de ne pas seulement créer des outils IA, mais de concevoir des solutions complètes : performantes, visuellement attrayantes et parfaitement intégrées à votre environnement de travail.",
    aiLabExperienceTitle: 'Projets et Réalisations',
    aiLabCalCostProTitle: 'CalCostPro - Application d\'Analyse de Coûts',
    aiLabCalCostProChallenge: 'Le Défi : Fournir aux entreprises de confection un outil précis pour calculer les coûts de production et optimiser les marges, une tâche souvent complexe et manuelle.',
    aiLabCalCostProSolution: 'La Solution IA : Développement d\'une application web SaaS (calcostpro.com) utilisant des modèles d\'IA pour analyser les données, prédire les coûts des matériaux et de la main-d\'œuvre, et suggérer des optimisations.',
    aiLabCalCostProResult: 'Le Résultat : Une plateforme intuitive qui permet aux utilisateurs de prendre des décisions éclairées rapidement, d\'améliorer leur rentabilité et de standardiser leurs processus de tarification.',
    aiLabThemeGenTitle: 'Générateur de Thèmes IA',
    aiLabThemeGenChallenge: 'Le Défi : Accélérer la phase initiale de branding en générant rapidement des palettes de couleurs et des associations de polices cohérentes.',
    aiLabThemeGenSolution: "La Solution IA : Création d'un outil qui, à partir d'un simple concept (ex: 'café bio pour cyclistes'), utilise un LLM (comme Gemini) pour proposer des directions artistiques complètes et justifiées.",
    aiLabThemeGenResult: 'Le Résultat : Un gain de temps considérable pour les designers et les entrepreneurs, leur permettant d\'explorer plusieurs pistes créatives en quelques secondes.',
    aiLabSkillsTitle: 'Outils et Compétences',
    aiLabSkills: ['Intégration d\'API (Google AI, OpenAI)', 'Prompt Engineering avancé', 'Développement de Chatbots personnalisés', 'Développement Full-Stack (Next.js, Firebase)', 'Conception UI/UX pour applications IA'],
    aiLabServicesTitle: 'Comment je peux aider votre entreprise',
    aiLabServiceDevTitle: 'Développement sur mesure',
    aiLabServiceDevText: "Création d'outils internes basés sur l'IA (aide à la rédaction, classification, automatisation) ou intégration de fonctionnalités IA dans vos applications web existantes.",
    aiLabServiceDesignTitle: 'Design et UX/UI pour l\'IA',
    aiLabServiceDesignText: "Conception d'interfaces conviviales pour des outils IA complexes, en s'assurant que l'outil s'intègre parfaitement à votre identité visuelle.",
    aiLabServiceStrategyTitle: 'Conseil et Stratégie',
    aiLabServiceStrategyText: "Évaluation de vos besoins pour choisir la bonne technologie IA, et accompagnement de vos équipes dans l'adoption des nouveaux outils.",
    aiLabCtaTitle: 'Prêt à discuter de votre projet IA ?',
    aiLabCtaText: 'Contactez-moi pour explorer comment l\'intelligence artificielle peut transformer votre entreprise.',
    aiLabCtaButton: 'Planifier une consultation',
    
    contactTitle: 'Parlons de votre projet',
    contactSubtitle: "N'hésitez pas à me contacter pour toute collaboration ou question.",
    contactEmail: "emmanuel@iung.li",
    contactNamePlaceholder: 'Votre nom',
    contactEmailPlaceholder: 'Votre email',
    contactMessagePlaceholder: 'Votre message',
    contactSendButton: 'Envoyer',
    contactSendingButton: 'Envoi en cours...',
    footerRights: 'Tous droits réservés.',
    formSuccessTitle: "Message envoyé !",
    formSuccessMessage: "Merci de m'avoir contacté. Je vous répondrai bientôt.",
    formErrorTitle: "Erreur d'envoi",
    formErrorMessage: "Une erreur s'est produite. Veuillez réessayer.",
    portfolioItems: portfolioItems.fr,
  },
  en: {
    aboutNav: 'About',
    portfolioNav: 'Portfolio',
    contactNav: 'Contact',
    aiLabNav: 'AI & Consulting',
    heroTitle: 'Emmanuel Iung',
    heroSubtitle: 'Graphic Designer, Web Developer, and AI Enthusiast with 20+ years of experience. I transform ideas into captivating visual experiences.',
    heroCta: 'Discover my work',
    aboutTitle: 'From Graphic Design to Building AI Applications',
    aboutParagraph1: 'I am Emmanuel Iung. With over two decades of experience in graphic design, I have cultivated a passion for visual aesthetics and clear communication. My journey began with traditional tools, but my curiosity quickly led me to the digital world. I embraced WordPress in its early days, developing websites that combined functionality and design.',
    aboutParagraph2: "Today, I am at the forefront of innovation, integrating artificial intelligence into my creations. I use Google Cloud tools to build intelligent and collaborative applications. My goal is to merge my design expertise with the power of AI to create unique and impactful solutions.",
    portfolioTitle: 'My Projects',
    portfolioFilterAll: 'All',
    portfolioFilterDesign: 'Graphic Design',
    portfolioFilterDev: 'Web Development',
    portfolioFilterAi: 'AI Projects',
    portfolioAiNotice: 'AI Tag Generator',

    aiLabTitle: 'Transforming Your Ideas into Concrete AI Tools',
    aiLabIntro: "My unique profile as a designer and developer allows me not just to create AI tools, but to design complete solutions: efficient, visually appealing, and perfectly integrated into your work environment.",
    aiLabExperienceTitle: 'Projects and Achievements',
    aiLabCalCostProTitle: 'CalCostPro - Cost Analysis Application',
    aiLabCalCostProChallenge: 'The Challenge: To provide apparel companies with a precise tool to calculate production costs and optimize margins, an often complex and manual task.',
    aiLabCalCostProSolution: 'The AI Solution: Development of a SaaS web application (calcostpro.com) using AI models to analyze data, predict material and labor costs, and suggest optimizations.',
    aiLabCalCostProResult: 'The Result: An intuitive platform that allows users to make informed decisions quickly, improve their profitability, and standardize their pricing processes.',
    aiLabThemeGenTitle: 'AI Theme Generator',
    aiLabThemeGenChallenge: 'The Challenge: To speed up the initial branding phase by quickly generating coherent color palettes and font pairings.',
    aiLabThemeGenSolution: "The AI Solution: Creation of a tool that, from a simple concept (e.g., 'organic coffee for cyclists'), uses an LLM (like Gemini) to propose complete and justified art directions.",
    aiLabThemeGenResult: 'The Result: A significant time saving for designers and entrepreneurs, allowing them to explore several creative paths in seconds.',
    aiLabSkillsTitle: 'Tools and Skills',
    aiLabSkills: ['API Integration (Google AI, OpenAI)', 'Advanced Prompt Engineering', 'Custom Chatbot Development', 'Full-Stack Development (Next.js, Firebase)', 'UI/UX Design for AI Applications'],
    aiLabServicesTitle: 'How I Can Help Your Business',
    aiLabServiceDevTitle: 'Custom Development',
    aiLabServiceDevText: "Creation of internal AI-based tools (writing assistance, classification, automation) or integration of AI features into your existing web applications.",
    aiLabServiceDesignTitle: 'AI-Focused Design and UX/UI',
    aiLabServiceDesignText: 'Designing user-friendly interfaces for complex AI tools, ensuring the tool integrates seamlessly with your visual identity.',
    aiLabServiceStrategyTitle: 'Consulting and Strategy',
    aiLabServiceStrategyText: 'Assessing your needs to choose the right AI technology, and supporting your teams in adopting new tools.',
    aiLabCtaTitle: 'Ready to discuss your AI project?',
    aiLabCtaText: 'Contact me to explore how artificial intelligence can transform your business.',
    aiLabCtaButton: 'Schedule a consultation',

    contactTitle: 'Let\'s talk about your project',
    contactSubtitle: 'Feel free to contact me for any collaboration or question.',
    contactEmail: "emmanuel@iung.li",
    contactNamePlaceholder: 'Your name',
    contactEmailPlaceholder: 'Your email',
    contactMessagePlaceholder: 'Your message',
    contactSendButton: 'Send',
    contactSendingButton: 'Sending...',
    footerRights: 'All rights reserved.',
    formSuccessTitle: "Message sent!",
    formSuccessMessage: "Thank you for reaching out. I will get back to you soon.",
    formErrorTitle: "Sending Error",
    formErrorMessage: "An error occurred. Please try again.",
    portfolioItems: portfolioItems.en,
  },
  es: {
    aboutNav: 'Sobre mí',
    portfolioNav: 'Portafolio',
    contactNav: 'Contacto',
    aiLabNav: 'IA & Consultoría',
    heroTitle: 'Emmanuel Iung',
    heroSubtitle: 'Diseñador Gráfico, Desarrollador Web y entusiasta de la IA con más de 20 años de experiencia. Transformo ideas en experiencias visuales cautivadoras.',
    heroCta: 'Descubre mi trabajo',
    aboutTitle: 'Del diseño gráfico a la creación de aplicaciones de IA',
    aboutParagraph1: 'Soy Emmanuel Iung. Con más de dos décadas de experiencia en diseño gráfico, he cultivado una pasión por la estética visual y la comunicación clara. Mi trayectoria comenzó con herramientas tradicionales, pero mi curiosidad me llevó rápidamente al mundo digital. Adopté WordPress en sus inicios, desarrollando sitios web que combinaban funcionalidad y diseño.',
    aboutParagraph2: 'Hoy, estoy a la vanguardia de la innovación, integrando la inteligencia artificial en mis creaciones. Utilizo las herramientas de Google Cloud para construir aplicaciones inteligentes y colaborativas. Mi objetivo es fusionar mi experiencia en diseño con el poder de la IA para crear soluciones únicas e impactantes.',
    portfolioTitle: 'Mis Proyectos',
    portfolioFilterAll: 'Todos',
    portfolioFilterDesign: 'Diseño Gráfico',
    portfolioFilterDev: 'Desarrollo Web',
    portfolioFilterAi: 'Proyectos IA',
    portfolioAiNotice: 'Generador de Etiquetas IA',
    
    aiLabTitle: 'Transformando sus ideas en herramientas de IA concretas',
    aiLabIntro: "Mi perfil único como diseñador y desarrollador me permite no solo crear herramientas de IA, sino diseñar soluciones completas: eficientes, visualmente atractivas y perfectamente integradas en su entorno de trabajo.",
    aiLabExperienceTitle: 'Proyectos y Logros',
    aiLabCalCostProTitle: 'CalCostPro - Aplicación de Análisis de Costos',
    aiLabCalCostProChallenge: 'El Desafío: Proporcionar a las empresas de confección una herramienta precisa para calcular los costos de producción y optimizar los márgenes, una tarea a menudo compleja y manual.',
    aiLabCalCostProSolution: 'La Solución de IA: Desarrollo de una aplicación web SaaS (calcostpro.com) que utiliza modelos de IA para analizar datos, predecir costos de materiales y mano de obra, y sugerir optimizaciones.',
    aiLabCalCostProResult: 'El Resultado: Una plataforma intuitiva que permite a los usuarios tomar decisiones informadas rápidamente, mejorar su rentabilidad y estandarizar sus procesos de fijación de precios.',
    aiLabThemeGenTitle: 'Generador de Temas de IA',
    aiLabThemeGenChallenge: 'El Desafío: Acelerar la fase inicial de branding generando rápidamente paletas de colores coherentes y combinaciones de fuentes.',
    aiLabThemeGenSolution: "La Solución de IA: Creación de una herramienta que, a partir de un concepto simple (ej: 'café orgánico para ciclistas'), utiliza un LLM (como Gemini) para proponer direcciones de arte completas y justificadas.",
    aiLabThemeGenResult: 'El Resultado: Un ahorro de tiempo significativo para diseñadores y emprendedores, permitiéndoles explorar varias vías creativas en segundos.',
    aiLabSkillsTitle: 'Herramientas y Competencias',
    aiLabSkills: ['Integración de API (Google AI, OpenAI)', 'Ingeniería de Prompts avanzada', 'Desarrollo de Chatbots personalizados', 'Desarrollo Full-Stack (Next.js, Firebase)', 'Diseño UI/UX para aplicaciones de IA'],
    aiLabServicesTitle: 'Cómo puedo ayudar a su empresa',
    aiLabServiceDevTitle: 'Desarrollo a medida',
    aiLabServiceDevText: 'Creación de herramientas internas basadas en IA (asistencia en redacción, clasificación, automatización) o integración de funcionalidades de IA en sus aplicaciones web existentes.',
    aiLabServiceDesignTitle: 'Diseño y UX/UI para IA',
    aiLabServiceDesignText: 'Diseño de interfaces fáciles de usar para herramientas de IA complejas, asegurando que la herramienta se integre perfectamente con su identidad visual.',
    aiLabServiceStrategyTitle: 'Consultoría y Estrategia',
    aiLabServiceStrategyText: 'Evaluación de sus necesidades para elegir la tecnología de IA adecuada y acompañamiento de sus equipos en la adopción de nuevas herramientas.',
    aiLabCtaTitle: '¿Listo para hablar de su proyecto de IA?',
    aiLabCtaText: 'Contácteme para explorar cómo la inteligencia artificial puede transformar su negocio.',
    aiLabCtaButton: 'Programar una consulta',

    contactTitle: 'Hablemos de tu proyecto',
    contactSubtitle: 'No dudes en contactarme para cualquier colaboración o pregunta.',
    contactEmail: "emmanuel@iung.li",
    contactNamePlaceholder: 'Tu nombre',
    contactEmailPlaceholder: 'Tu correo electrónico',
    contactMessagePlaceholder: 'Tu mensaje',
    contactSendButton: 'Enviar',
    contactSendingButton: 'Enviando...',
    footerRights: 'Todos los derechos reservados.',
    formSuccessTitle: "¡Mensaje enviado!",
    formSuccessMessage: "Gracias por contactarme. Te responderé pronto.",
    formErrorTitle: "Error al enviar",
    formErrorMessage: "Ocurrió un error. Por favor, inténtalo de nuevo.",
    portfolioItems: portfolioItems.es,
  },
};

    