import type { PortfolioData } from './types';

export const portfolioItems: PortfolioData = {
    fr: [
      {
        id: 1,
        title: 'Branding pour "NOE"',
        description: "Création d'un visuel complet pour un cabinet comptable, incluant logo et charte graphique.",
        imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
        featuredImageUrl: '/portfolio/p1-1.jpg',
        imageHints: ['design logo', 'branding entreprise'],
        tags: ['Branding', 'Logo', 'Identité Visuelle'],
        category: 'design',
      },
      {
        id: 2,
        title: 'Brochure pour projet architectural',
        description: "Réalisation d'une brochure de présentation pour un appel d'offre de projet architectural.",
        imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
        featuredImageUrl: '/portfolio/p2-1.jpg',
        imageHints: ['maquette brochure', 'design éditorial', 'impression architecture', 'livret professionnel', 'brochure moderne', 'design épuré', 'présentation entreprise'],
        tags: ['Edition', 'Brochure', 'Mise en page', 'Architecture'],
        category: 'design',
      },
      {
        id: 3,
        title: 'Packaging "Life Essential"',
        description: "Création d'une gamme de packaging pour une marque qui élabore des huiles essentielles.",
        imageUrls: ['/portfolio/p3-1.jpg', '/portfolio/p3-2.jpg'],
        featuredImageUrl: '/portfolio/p3-1.jpg',
        imageHints: ['packaging produit', 'branding cosmétique'],
        tags: ['Packaging', 'Design Produit', 'Huiles Essentielles'],
        category: 'design',
      },
      {
        id: 4,
        title: 'Identité visuelle "SABSA"',
        description: "Réalisation de l'identité visuel complète avec un manuel d'utilisation pour la société des aéroports de Bolivie, déclinasion du logo sur tous les supports",
        imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
        featuredImageUrl: '/portfolio/p4-1.jpg',
        imageHints: ['design affiche', 'sensibilisation graphique', 'typographie audacieuse'],
        tags: ['Branding', 'Logo', 'Identité Visuelle'],
        category: 'design',
      },
      {
        id: 5,
        title: 'Logo "Chichi Pizza"',
        description: "Création d'un visuel complet pour une jeune entreprise de livraison à domicile, incluant logo, charte graphique et supports marketing.",
        imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
        featuredImageUrl: '/portfolio/p5-1.jpg',
        imageHints: ['logo pizza', 'branding alimentaire', 'identité restaurant', 'design livraison', 'logo moderne'],
        tags: ['Logo', 'Branding', 'Restauration', 'Marketing'],
        category: 'design',
      },
      {
        id: 6,
        title: 'Site web wordpress',
        description: "Development of an e-commerce site for the online sale of handcrafted fashion accessories",
        imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
        featuredImageUrl: '/portfolio/p6-1.jpg',
        imageHints: ['création artisanales', 'design site web'],
        tags: ['Développement Web', 'Wordpress'],
        category: 'dev',
      },
      {
        id: 7,
        title: 'Logo de bijouterie',
        description: "Réalisation d'un logo pour une jeune société de creation de bijoux fantaisie",
        imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
        featuredImageUrl: '/portfolio/p7-1.jpg',
        imageHints: ['outil ia', 'palette couleurs'],
        tags: ['IA', 'Outil de Design', 'Créativité'],
        category: 'design',
      },
      {
        id: 8,
        title: 'Site de consultation en ligne',
        description: "Développement d'un site e-commerce complet avec WordPress et WooCommerce, incluant la personnalisation du thème et l'intégration de plugins.",
        imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
        featuredImageUrl: '/portfolio/p8-1.jpg',
        imageHints: ['boutique ecommerce', 'page produit', 'magasin en ligne', 'site web mode'],
        tags: ['Développement Web', 'WordPress', 'E-commerce', 'WooCommerce'],
        category: 'dev',
      },
      {
        id: 9,
        title: 'CalCostPro - Application Web IA',
        description: "Développement de CalCostPro (calcostpro.com), une application web utilisant l'IA pour le calcul précis de prix et l'analyse des coûts dans le secteur de la confection.",
        imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
        featuredImageUrl: '/portfolio/p9-1.jpg',
        imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
        tags: ['Développement Web', 'IA', 'SaaS', 'Firebase', 'Next.js', 'Analyse de données'],
        category: 'ai',
      },
      {
        id: 10,
        title: 'Packaging Plaque de Chocolat',
        description: "Création d'un design de packaging pour une nouvelle marque de chocolat artisanal à la spiruline.",
        imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
        featuredImageUrl: '/portfolio/p10-1.jpg',
        imageHints: ['packaging chocolat', 'design spiruline', 'emballage produit'],
        tags: ['Packaging', 'Design Produit', 'Chocolat', 'Branding'],
        category: 'design',
      },
      /*
      {
        id: 11,
        title: 'Projet 11',
        description: 'Description du projet 11. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
        featuredImageUrl: '/portfolio/p11-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 12,
        title: 'Projet 12',
        description: 'Description du projet 12. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
        featuredImageUrl: '/portfolio/p12-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 13,
        title: 'Projet 13',
        description: 'Description du projet 13. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
        featuredImageUrl: '/portfolio/p13-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 14,
        title: 'Projet 14',
        description: 'Description du projet 14. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
        featuredImageUrl: '/portfolio/p14-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 15,
        title: 'Projet 15',
        description: 'Description du projet 15. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
        featuredImageUrl: '/portfolio/p15-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 16,
        title: 'Projet 16',
        description: 'Description du projet 16. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
        featuredImageUrl: '/portfolio/p16-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 17,
        title: 'Projet 17',
        description: 'Description du projet 17. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
        featuredImageUrl: '/portfolio/p17-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 18,
        title: 'Projet 18',
        description: 'Description du projet 18. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
        featuredImageUrl: '/portfolio/p18-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 19,
        title: 'Projet 19',
        description: 'Description du projet 19. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
        featuredImageUrl: '/portfolio/p19-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 20,
        title: 'Projet 20',
        description: 'Description du projet 20. À remplacer par la description de votre projet.',
        imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
        featuredImageUrl: '/portfolio/p20-1.jpg',
        imageHints: ['aperçu projet', 'détail projet'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      */
    ],
    en: [
      {
        id: 1,
        title: 'Branding for "NOE"',
        description: "Creation of a complete visual identity for an accounting firm, including logo and brand guidelines.",
        imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
        featuredImageUrl: '/portfolio/p1-1.jpg',
        imageHints: ['logo design', 'corporate branding'],
        tags: ['Branding', 'Logo', 'Visual Identity'],
        category: 'design',
      },
      {
        id: 2,
        title: 'Architectural Project Brochure',
        description: "Layout of a presentation brochure for an architectural project bid.",
        imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
        featuredImageUrl: '/portfolio/p2-1.jpg',
        imageHints: ['brochure layout', 'editorial design', 'architecture print', 'professional booklet', 'modern brochure', 'clean design', 'corporate presentation'],
        tags: ['Publishing', 'Brochure', 'Layout', 'Architecture'],
        category: 'design',
      },
      {
        id: 3,
        title: 'Life Essential" Packaging',
        description: "Creation of a packaging range for a brand of essential oils.",
        imageUrls: ['/portfolio/p3-1.jpg'],
        featuredImageUrl: '/portfolio/p3-1.jpg',
        imageHints: ['product packaging', 'cosmetic branding'],
        tags: ['Packaging', 'Product Design', 'Essential Oils'],
        category: 'design',
      },
      {
        id: 4,
        title: 'SABSA" Visual Identity',
        description: "Art direction for an environmental awareness campaign, creating impactful visuals for social media.",
        imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
        featuredImageUrl: '/portfolio/p4-1.jpg',
        imageHints: ['poster design', 'social campaign', 'graphic awareness', 'environmental art', 'bold typography'],
        tags: ['Visual Identity', 'Art Direction', 'Social Campaign'],
        category: 'design',
      },
      {
        id: 5,
        title: '"Chichi Pizza" Logo',
        description: "Creation of a complete visual identity for a new home delivery company, including logo, graphic charter, and marketing materials.",
        imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
        featuredImageUrl: '/portfolio/p5-1.jpg',
        imageHints: ['pizza logo', 'food branding', 'restaurant identity', 'takeaway design', 'modern logo'],
        tags: ['Logo', 'Branding', 'Food & Beverage', 'Marketing'],
        category: 'design',
      },
      {
        id: 6,
        title: 'Artist Website',
        description: 'Development of a portfolio website for an artist',
        imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
        featuredImageUrl: '/portfolio/p6-1.jpg',
        imageHints: ['art gallery', 'website design'],
        tags: ['Web Development', 'AI', 'Next.js', 'Portfolio'],
        category: 'dev',
      },
      {
        id: 7,
        title: 'AI Theme Generator',
        description: "Web application that generates color palettes and font suggestions based on a concept, using AI.",
        imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
        featuredImageUrl: '/portfolio/p7-1.jpg',
        imageHints: ['ai tool', 'color palette'],
        tags: ['AI', 'Design Tool', 'Genkit', 'Creativity'],
        category: 'design',
      },
      {
        id: 8,
        title: 'Online shop Site',
        description: 'Development of a complete e-commerce site with WordPress and WooCommerce, including theme customization and plugin integration.',
        imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
        featuredImageUrl: '/portfolio/p8-1.jpg',
        imageHints: ['ecommerce store', 'product page', 'online shop', 'fashion website'],
        tags: ['Web Development', 'WordPress', 'E-commerce', 'WooCommerce'],
        category: 'dev',
      },
      {
        id: 9,
        title: 'CalCostPro - AI Web Application',
        description: 'Development of CalCostPro (calcostpro.com), an AI-powered web application for accurate price calculation and cost analysis in the apparel industry.',
        imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
        featuredImageUrl: '/portfolio/p9-1.jpg',
        imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
        tags: ['Web Development', 'AI', 'SaaS', 'Firebase', 'Next.js', 'Data Analysis'],
        category: 'ai',
      },
      {
        id: 10,
        title: 'Chocolate Bar Packaging',
        description: 'Packaging design for a new brand of artisanal chocolate with spirulina.',
        imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
        featuredImageUrl: '/portfolio/p10-1.jpg',
        imageHints: ['chocolate packaging', 'spirulina design', 'product wrapping'],
        tags: ['Packaging', 'Product Design', 'Chocolate', 'Branding'],
        category: 'design',
      },
      /*
      {
        id: 11,
        title: 'Project 11',
        description: 'Description for project 11. Replace with your project description.',
        imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
        featuredImageUrl: '/portfolio/p11-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 12,
        title: 'Project 12',
        description: 'Description for project 12. Replace with your project description.',
        imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
        featuredImageUrl: '/portfolio/p12-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 13,
        title: 'Project 13',
        description: 'Description for project 13. Replace with your project description.',
        imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
        featuredImageUrl: '/portfolio/p13-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 14,
        title: 'Project 14',
        description: 'Description for project 14. Replace with your project description.',
        imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
        featuredImageUrl: '/portfolio/p14-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 15,
        title: 'Project 15',
        description: 'Description for project 15. Replace with your project description.',
        imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
        featuredImageUrl: '/portfolio/p15-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 16,
        title: 'Project 16',
        description: 'Description for project 16. Replace with your project description.',
        imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
        featuredImageUrl: '/portfolio/p16-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 17,
        title: 'Project 17',
        description: 'Description for project 17. Replace with your project description.',
        imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
        featuredImageUrl: '/portfolio/p17-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'design',
      },
      {
        id: 18,
        title: 'Project 18',
        description: 'Description for project 18. Replace with your project description.',
        imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
        featuredImageUrl: '/portfolio/p18-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      {
        id: 19,
        title: 'Project 19',
        description: 'Description for project 19. Replace with your project description.',
        imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
        featuredImageUrl: '/portfolio/p19-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'ai',
      },
      {
        id: 20,
        title: 'Project 20',
        description: 'Description for project 20. Replace with your project description.',
        imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
        featuredImageUrl: '/portfolio/p20-1.jpg',
        imageHints: ['project preview', 'project detail'],
        tags: ['Tag 1', 'Tag 2', 'Tag 3'],
        category: 'dev',
      },
      */
    ],
    es: [
      {
        id: 1,
        title: 'Branding para "NOE"',
        description: "Creación de una identidad visual completa para una firma de contabilidad, incluyendo logo y manual de marca.",
        imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
        featuredImageUrl: '/portfolio/p1-1.jpg',
        imageHints: ['diseño de logo', 'branding corporativo'],
        tags: ['Branding', 'Logo', 'Identidad Visual'],
        category: 'design',
      },
      {
        id: 2,
        title: 'Folleto de proyecto arquitectónico',
        description: "Realización de un folleto de presentación para una licitación de proyecto de arquitectura.",
        imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
        featuredImageUrl: '/portfolio/p2-1.jpg',
        imageHints: ['maquetación de folleto', 'diseño editorial', 'impresión arquitectura', 'folleto profesional', 'folleto moderno', 'diseño limpio', 'presentación corporativa'],
        tags: ['Edición', 'Folleto', 'Maquetación', 'Arquitectura'],
        category: 'design',
      },
      {
        id: 3,
        title: 'Packaging "Life Essential"',
        description: "Creación de una gama de packaging para una marca que elabora aceites esenciales.",
        imageUrls: ['/portfolio/p3-1.jpg'],
        featuredImageUrl: '/portfolio/p3-1.jpg',
        imageHints: ['packaging de producto', 'branding de cosméticos'],
        tags: ['Packaging', 'Diseño de Producto', 'Aceites Esenciales'],
        category: 'design',
      },
      {
        id: 4,
        title: 'Identidad visual "SABSA"',
        description: "Creacion de una identidad visual por los aeropuertos de Bolivia con un aplicacion en todo tipo de soportes",
        imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
        featuredImageUrl: '/portfolio/p4-1.jpg',
        imageHints: ['diseño de póster', 'campaña social', 'conciencia gráfica', 'arte ambiental', 'tipografía audaz'],
        tags: ['Identidad Visual', 'Dirección de Arte', 'Campaña Social'],
        category: 'design',
      },
      {
        id: 5,
        title: 'Logo "Chichi Pizza"',
        description: "Creación de una identidad visual completa para una nueva empresa de reparto a domicilio, incluyendo logo, manual de marca y soportes de marketing.",
        imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
        featuredImageUrl: '/portfolio/p5-1.jpg',
        imageHints: ['pizza logo', 'branding de alimentos', 'identidad de restaurante', 'diseño para llevar', 'logo moderno'],
        tags: ['Logo', 'Branding', 'Restauración', 'Marketing'],
        category: 'design',
      },
      {
        id: 6,
        title: 'Sitio web de creacion de accesorios de moda',
        description: 'Desarrollo de un sitio web de accesorios de moda.',
        imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
        featuredImageUrl: '/portfolio/p6-1.jpg',
        imageHints: ['arte', 'confección', 'diseño de sitio web'],
        tags: ['Desarrollo Web', 'wordpress', 'e-commercio'],
        category: 'dev',
      },
       {
        id: 7,
        title: 'Bisutería',
        description: "Aplicación web que genera paletas de colores y sugerencias de fuentes basadas en un concepto, usando IA.",
        imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
        featuredImageUrl: '/portfolio/p7-1.jpg',
        imageHints: ['herramienta ia', 'paleta de colores'],
        tags: ['IA', 'Herramienta de Diseño', 'Genkit', 'Creatividad'],
        category: 'design',
      },
      {
        id: 8,
        title: 'Sitio de consultacion en linea',
        description: 'Desarrollo de un sitio de comercio electrónico completo con WordPress y WooCommerce, incluyendo personalización del tema e integración de plugins.',
        imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
        featuredImageUrl: '/portfolio/p8-1.jpg',
        imageHints: ['tienda ecommerce', 'página de producto', 'tienda online', 'sitio web de moda'],
        tags: ['Desarrollo Web', 'WordPress', 'E-commerce', 'WooCommerce'],
        category: 'dev',
      },
      {
        id: 9,
        title: 'CalCostPro - Aplicación Web con IA',
        description: 'Desarrollo de CalCostPro (calcostpro.com), una aplicación web que utiliza IA para el cálculo preciso de precios y el análisis de costos en la industria de la confección.',
        imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
        featuredImageUrl: '/portfolio/p9-1.jpg',
        imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
        tags: ['Desarrollo Web', 'IA', 'SaaS', 'Firebase', 'Next.js', 'Análisis de Datos'],
        category: 'ai',
      },
      {
        id: 10,
        title: 'Packaging de tableta de chocolate',
        description: 'Diseño de packaging para una nueva marca de chocolate artesanal con espirulina.',
        imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
        featuredImageUrl: '/portfolio/p10-1.jpg',
        imageHints: ['packaging de chocolate', 'diseño espirulina', 'envoltura de producto'],
        tags: ['Packaging', 'Diseño de Producto', 'Chocolate', 'Branding'],
        category: 'design',
      },
      /*
      {
        id: 11,
        title: 'Proyecto 11',
        description: 'Descripción del proyecto 11. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
        featuredImageUrl: '/portfolio/p11-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'design',
      },
      {
        id: 12,
        title: 'Proyecto 12',
        description: 'Descripción del proyecto 12. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
        featuredImageUrl: '/portfolio/p12-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'dev',
      },
      {
        id: 13,
        title: 'Proyecto 13',
        description: 'Descripción del proyecto 13. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
        featuredImageUrl: '/portfolio/p13-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'ai',
      },
      {
        id: 14,
        title: 'Proyecto 14',
        description: 'Descripción del proyecto 14. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
        featuredImageUrl: '/portfolio/p14-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'design',
      },
      {
        id: 15,
        title: 'Proyecto 15',
        description: 'Descripción del proyecto 15. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
        featuredImageUrl: '/portfolio/p15-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'dev',
      },
      {
        id: 16,
        title: 'Proyecto 16',
        description: 'Descripción del proyecto 16. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
        featuredImageUrl: '/portfolio/p16-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'ai',
      },
      {
        id: 17,
        title: 'Proyecto 17',
        description: 'Descripción del proyecto 17. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
        featuredImageUrl: '/portfolio/p17-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'design',
      },
      {
        id: 18,
        title: 'Proyecto 18',
        description: 'Descripción del proyecto 18. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
        featuredImageUrl: '/portfolio/p18-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'dev',
      },
      {
        id: 19,
        title: 'Proyecto 19',
        description: 'Descripción del proyecto 19. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
        featuredImageUrl: '/portfolio/p19-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'ai',
      },
      {
        id: 20,
        title: 'Proyecto 20',
        description: 'Descripción del proyecto 20. Reemplazar con la descripción de su proyecto.',
        imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
        featuredImageUrl: '/portfolio/p20-1.jpg',
        imageHints: ['vista previa proyecto', 'detalle proyecto'],
        tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
        category: 'dev',
      },
      */
    ],
  };

    

    
