import type { PortfolioData } from './types';

export const portfolioItems: PortfolioData = {
  fr: [
    {
      id: 1,
      title: 'Branding pour "NOE"',
      description: "Création d'un visuel complet pour un cabinet comptable, incluant logo et charte graphique.",
      imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
      featuredImageUrl: '/portfolio/p1-1.jpg',
      imageHints: ['design logo', 'branding entreprise'],
      tags: ['Branding', 'Logo', 'Identité Visuelle'],
      category: 'design',
    },
    {
      id: 2,
      title: 'Brochure pour projet architectural',
      description: "Réalisation d'une brochure de présentation pour un appel d'offre de projet architectural.",
      imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
      featuredImageUrl: '/portfolio/p2-1.jpg',
      imageHints: ['maquette brochure', 'design éditorial', 'impression architecture', 'livret professionnel', 'brochure moderne', 'design épuré', 'présentation entreprise'],
      tags: ['Edition', 'Brochure', 'Mise en page', 'Architecture'],
      category: 'design',
    },
    {
      id: 3,
      title: 'Packaging "Life Essential"',
      description: "Création d'une gamme de packaging pour une marque qui élabore des huiles essentielles.",
      imageUrls: ['/portfolio/p3-1.jpg', '/portfolio/p3-2.jpg'],
      featuredImageUrl: '/portfolio/p3-1.jpg',
      imageHints: ['packaging produit', 'branding cosmétique'],
      tags: ['Packaging', 'Design Produit', 'Huiles Essentielles'],
      category: 'design',
    },
    {
      id: 4,
      title: 'Identité visuelle "SABSA"',
      description: "Réalisation de l'identité visuel complète avec un manuel d'utilisation pour la société des aéroports de Bolivie, déclinasion du logo sur tous les supports",
      imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
      featuredImageUrl: '/portfolio/p4-1.jpg',
      imageHints: ['design affiche', 'sensibilisation graphique', 'typographie audacieuse'],
      tags: ['Branding', 'Logo', 'Identité Visuelle'],
      category: 'design',
    },
    {
      id: 5,
      title: 'Logo "Chichi Pizza"',
      description: "Création d'un visuel complet pour une jeune entreprise de livraison à domicile, incluant logo, charte graphique et supports marketing.",
      imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
      featuredImageUrl: '/portfolio/p5-1.jpg',
      imageHints: ['logo pizza', 'branding alimentaire', 'identité restaurant', 'design livraison', 'logo moderne'],
      tags: ['Logo', 'Branding', 'Restauration', 'Marketing'],
      category: 'design',
    },
    {
      id: 6,
      title: 'Boutique E-commerce Loampsi',
      description: "Développement d'une boutique en ligne sur mesure pour une marque artisanale d'accessoires de mode et maroquinerie.",
      longDescription: "Création et intégration d'un site e-commerce élégant et immersif avec WordPress et WooCommerce pour la marque Loampsi.\n\nLe projet comprend la conception d'un thème sur mesure valorisant les créations faites main, la configuration d'un catalogue produit avec fiches détaillées, la gestion des stocks, la mise en place d'un tunnel d'achat optimisé et l'intégration de moyens de paiement sécurisés.",
      imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
      featuredImageUrl: '/portfolio/p6-1.jpg',
      imageHints: ['créations artisanales', 'design site web e-commerce'],
      tags: ['Développement Web', 'WordPress', 'WooCommerce', 'E-commerce'],
      category: 'dev',
      liveUrl: 'https://loampsi.com',
      liveUrlLabel: 'Visiter loampsi.com',
      features: [
        'Boutique en ligne complète sous WordPress & WooCommerce',
        'Catalogue de produits avec photos haute résolution et déclinaisons',
        'Tunnel d\'achat fluide et passerelles de paiement sécurisées',
        'Interface d\'administration pour gestion des commandes et stocks',
      ],
    },
    {
      id: 7,
      title: 'Logo de bijouterie',
      description: "Réalisation d'un logo pour une jeune société de creation de bijoux fantaisie",
      imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
      featuredImageUrl: '/portfolio/p7-1.jpg',
      imageHints: ['outil ia', 'palette couleurs'],
      tags: ['IA', 'Outil de Design', 'Créativité'],
      category: 'design',
    },
    {
      id: 8,
      title: 'Site de consultation en ligne',
      description: "Développement d'un site e-commerce complet avec WordPress et WooCommerce, incluant la personnalisation du thème et l'intégration de plugins.",
      imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
      featuredImageUrl: '/portfolio/p8-1.jpg',
      imageHints: ['boutique ecommerce', 'page produit', 'magasin en ligne', 'site web mode'],
      tags: ['Développement Web', 'WordPress', 'E-commerce', 'WooCommerce'],
      category: 'dev',
    },
    {
      id: 9,
      title: 'CalCostPro - Application Web IA',
      description: "Développement de CalCostPro (calcostpro.com), une application web utilisant l'IA pour le calcul précis de prix et l'analyse des coûts dans le secteur de la confection textile.",
      longDescription: "CalCostPro est une application SaaS d'ingénierie financière développée spécifiquement pour l'industrie de la confection et du textile. Elle permet de décomposer précisément le coût de revient d'une pièce d'habillement (tissus, consommables, main d'œuvre, temps de patronage, chutes) et d'exploiter des algorithmes d'IA (Gemini) pour recommander des prix de vente optimisés et déceler les anomalies de rentabilité.",
      imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
      featuredImageUrl: '/portfolio/p9-1.jpg',
      imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
      tags: ['Développement Web', 'IA', 'SaaS', 'Firebase', 'Next.js', 'Analyse de données'],
      category: 'ai',
      liveUrl: 'https://calcostpro.com',
      liveUrlLabel: 'Lancer calcostpro.com',
      features: [
        'Calcul automatisé des coûts directs et consommations matières',
        'Simulateur prédictif de marges et prix de vente recommandés',
        'Assistance IA (Gemini) pour analyse de rentabilité et détection d\'écarts',
        'Génération de devis détaillés et exports fiches techniques',
      ],
    },
    {
      id: 10,
      title: 'Packaging Plaque de Chocolat',
      description: "Création d'un design de packaging pour une nouvelle marque de chocolat artisanal à la spiruline.",
      imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
      featuredImageUrl: '/portfolio/p10-1.jpg',
      imageHints: ['packaging chocolat', 'design spiruline', 'emballage produit'],
      tags: ['Packaging', 'Design Produit', 'Chocolat', 'Branding'],
      category: 'design',
    },
    {
      id: 11,
      title: 'CFAB | Cercle Français d\'Affaires en Bolivie',
      description: "Conception et développement de la plateforme web institutionnelle pour le Cercle Français d'Affaires en Bolivie, réseau national et bilatéral reliant dirigeants, investisseurs et experts.",
      longDescription: "Le Cercle Français d'Affaires en Bolivie (CFAB) fédère les entreprises, entrepreneurs et acteurs économiques bilatéraux entre la France et la Bolivie.\n\nCe projet de développement web a eu pour vocation de concevoir une vitrine institutionnelle de haut niveau : valorisation des commissions sectorielles (énergie, mines, agroalimentaire, services), publication des opportunités d'affaires, annuaire des membres et système d'adhésion en ligne.\n\nL'accent a été mis sur une interface contemporaine et solennelle, une vitesse de chargement instantanée, une typographie soignée (Plus Jakarta Sans) et une ergonomie optimale pour la consultation sur smartphone et tablette.",
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg', '/portfolio/p11-3.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['site institutionnel cfab', 'page commissions et actualités', 'annuaire et adhésion en ligne'],
      tags: ['Développement Web', 'Site Institutionnel', 'Réseau d\'affaires', 'UI/UX'],
      category: 'dev',
      liveUrl: 'https://cfab.iung.li',
      liveUrlLabel: 'Visiter cfab.iung.li',
      features: [
        'Architecture web réactive et performante sans rechargement de page',
        'Mise en avant des commissions sectorielles et actualités économiques',
        'Espace de présentation des partenaires institutionnels (Chambre, Ambassade)',
        'Formulaires d\'adhésion et de contact d\'affaires qualifiés',
        'Optimisation SEO et design 100% responsive adapté aux décideurs',
      ],
    },
    {
      id: 12,
      title: 'Site web Intikuna',
      description: "Création du site web vitrine pour Intikuna : identité visuelle soignée, mise en avant des prestations de conseil et expérience de navigation responsive.",
      longDescription: "Intikuna est une structure dédiée au conseil, à l'accompagnement stratégique et aux services professionnels.\n\nLe mandat de développement consistait à concevoir une présence digitale percutante, renforçant la crédibilité de la marque auprès de ses clients et partenaires. Le site structure l'ensemble des offres d'accompagnement de manière didactique, avec un parcours utilisateur fluide orienté vers la prise de contact.\n\nUne attention particulière a été apportée à la performance d'affichage, aux micro-interactions et à la parfaite lisibilité sur l'ensemble des supports mobiles.",
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['site vitrine intikuna', 'catalogue prestations de conseil'],
      tags: ['Développement Web', 'Site Vitrine', 'Conseil', 'Responsive Design'],
      category: 'dev',
      liveUrl: 'https://intikuna.vercel.app/',
      liveUrlLabel: 'Visiter intikuna.vercel.app',
      features: [
        'Design sur mesure reflétant l\'expertise et la rigueur du cabinet',
        'Structure éditoriale claire avec présentation des pôles de compétences',
        'Parcours de conversion direct avec formulaire de contact',
        'Performance web optimale et temps de chargement ultra-rapide',
        'Compatibilité multi-navigateurs et fluidité tactile totale',
      ],
    },
    {
      id: 13,
      title: 'Portail & Gestion Sportive Assofoot',
      description: "Développement complet d'une application web de gestion sportive pour l'association Assofoot : suivi des compétitions, calendrier des matchs en direct, équipes et résultats.",
      longDescription: "Assofoot organise et administre des championnats de football réunissant de nombreux clubs, arbitres et passionnés. La gestion traditionnelle sur tableurs et groupes informels nécessitait une digitalisation complète pour centraliser l'information en temps réel.\n\nL'application web développée intègre la gestion dynamique des championnats par catégorie, le calendrier temps réel des rencontres (dates, heures précises, terrains), les fiches détaillées des clubs et des joueurs (postes, numéros de maillot, photos), ainsi que les résultats et classements actualisés après chaque journée de match.\n\nUn module de partage instantané des fiches de match via WhatsApp a également été intégré pour diffuser les convocations aux capitaines et supporters en un clic.",
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg', '/portfolio/p13-3.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['portail assofoot accueil', 'calendrier des matchs en direct', 'fiches équipes et classements'],
      tags: ['Développement Web', 'Sport', 'Application Web', 'Temps Réel', 'PWA'],
      category: 'dev',
      liveUrl: 'https://assofoot.iung.li',
      liveUrlLabel: 'Visiter assofoot.iung.li',
      features: [
        'Gestion dynamique des championnats, catégories et saisons sportives',
        'Calendrier des matchs temps réel avec filtres par date, terrain et statut',
        'Fiches d\'équipes et annuaire des joueurs avec numéros, postes et photos',
        'Tableau des classements et statistiques de compétition mis à jour automatiquement',
        'Génération et partage en un clic des fiches de match sur WhatsApp',
        'Interface mobile-first ultra-rapide pensée pour l\'usage au bord du terrain',
      ],
    },
    /*
    {
      id: 11,
      title: 'Projet 11',
      description: 'Description du projet 11. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 12,
      title: 'Projet 12',
      description: 'Description du projet 12. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 13,
      title: 'Projet 13',
      description: 'Description du projet 13. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 14,
      title: 'Projet 14',
      description: 'Description du projet 14. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
      featuredImageUrl: '/portfolio/p14-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 15,
      title: 'Projet 15',
      description: 'Description du projet 15. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
      featuredImageUrl: '/portfolio/p15-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 16,
      title: 'Projet 16',
      description: 'Description du projet 16. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
      featuredImageUrl: '/portfolio/p16-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 17,
      title: 'Projet 17',
      description: 'Description du projet 17. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
      featuredImageUrl: '/portfolio/p17-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 18,
      title: 'Projet 18',
      description: 'Description du projet 18. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
      featuredImageUrl: '/portfolio/p18-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 19,
      title: 'Projet 19',
      description: 'Description du projet 19. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
      featuredImageUrl: '/portfolio/p19-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 20,
      title: 'Projet 20',
      description: 'Description du projet 20. À remplacer par la description de votre projet.',
      imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
      featuredImageUrl: '/portfolio/p20-1.jpg',
      imageHints: ['aperçu projet', 'détail projet'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    */
  ],
  en: [
    {
      id: 1,
      title: 'Branding for "NOE"',
      description: "Creation of a complete visual identity for an accounting firm, including logo and brand guidelines.",
      imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
      featuredImageUrl: '/portfolio/p1-1.jpg',
      imageHints: ['logo design', 'corporate branding'],
      tags: ['Branding', 'Logo', 'Visual Identity'],
      category: 'design',
    },
    {
      id: 2,
      title: 'Architectural Project Brochure',
      description: "Layout of a presentation brochure for an architectural project bid.",
      imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
      featuredImageUrl: '/portfolio/p2-1.jpg',
      imageHints: ['brochure layout', 'editorial design', 'architecture print', 'professional booklet', 'modern brochure', 'clean design', 'corporate presentation'],
      tags: ['Publishing', 'Brochure', 'Layout', 'Architecture'],
      category: 'design',
    },
    {
      id: 3,
      title: 'Life Essential" Packaging',
      description: "Creation of a packaging range for a brand of essential oils.",
      imageUrls: ['/portfolio/p3-1.jpg'],
      featuredImageUrl: '/portfolio/p3-1.jpg',
      imageHints: ['product packaging', 'cosmetic branding'],
      tags: ['Packaging', 'Product Design', 'Essential Oils'],
      category: 'design',
    },
    {
      id: 4,
      title: 'SABSA" Visual Identity',
      description: "Art direction for an environmental awareness campaign, creating impactful visuals for social media.",
      imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
      featuredImageUrl: '/portfolio/p4-1.jpg',
      imageHints: ['poster design', 'social campaign', 'graphic awareness', 'environmental art', 'bold typography'],
      tags: ['Visual Identity', 'Art Direction', 'Social Campaign'],
      category: 'design',
    },
    {
      id: 5,
      title: '"Chichi Pizza" Logo',
      description: "Creation of a complete visual identity for a new home delivery company, including logo, graphic charter, and marketing materials.",
      imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
      featuredImageUrl: '/portfolio/p5-1.jpg',
      imageHints: ['pizza logo', 'food branding', 'restaurant identity', 'takeaway design', 'modern logo'],
      tags: ['Logo', 'Branding', 'Food & Beverage', 'Marketing'],
      category: 'design',
    },
    {
      id: 6,
      title: 'Loampsi Online Boutique',
      description: 'Design and development of an e-commerce website for fashion accessories and bespoke creations.',
      longDescription: 'Loampsi is an online boutique specializing in trendy accessories and custom fashion pieces.\n\nThe project involved developing a fast, responsive e-commerce platform with a user-friendly product catalog, streamlined checkout flow, secure payment integration, and a dedicated back-office for managing inventory and orders.',
      imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
      featuredImageUrl: '/portfolio/p6-1.jpg',
      imageHints: ['fashion boutique', 'ecommerce design', 'accessories store'],
      tags: ['Web Development', 'E-commerce', 'WooCommerce', 'UI/UX'],
      category: 'dev',
      liveUrl: 'https://loampsi.com',
      liveUrlLabel: 'Visit loampsi.com',
      features: [
        'Full-featured e-commerce store built with WordPress & WooCommerce',
        'High-resolution product catalog with variants and clear stock status',
        'Streamlined checkout process and secure payment gateways',
        'Intuitive administration panel for order and customer management',
      ],
    },
    {
      id: 7,
      title: 'AI Theme Generator',
      description: "Web application that generates color palettes and font suggestions based on a concept, using AI.",
      imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
      featuredImageUrl: '/portfolio/p7-1.jpg',
      imageHints: ['ai tool', 'color palette'],
      tags: ['AI', 'Design Tool', 'Genkit', 'Creativity'],
      category: 'design',
    },
    {
      id: 8,
      title: 'Online shop Site',
      description: 'Development of a complete e-commerce site with WordPress and WooCommerce, including theme customization and plugin integration.',
      imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
      featuredImageUrl: '/portfolio/p8-1.jpg',
      imageHints: ['ecommerce store', 'product page', 'online shop', 'fashion website'],
      tags: ['Web Development', 'WordPress', 'E-commerce', 'WooCommerce'],
      category: 'dev',
    },
    {
      id: 9,
      title: 'CalCostPro - AI Web Application',
      description: 'Development of CalCostPro (calcostpro.com), an AI-powered SaaS application for accurate garment costing and pricing analysis.',
      longDescription: 'CalCostPro is a financial engineering SaaS application tailored specifically for the apparel and textile manufacturing industry. It allows businesses to break down unit production costs with precision (fabrics, trims, labor, patterns, waste) and leverages Gemini AI algorithms to recommend optimal selling prices and highlight profitability bottlenecks.',
      imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
      featuredImageUrl: '/portfolio/p9-1.jpg',
      imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
      tags: ['Web Development', 'AI', 'SaaS', 'Firebase', 'Next.js', 'Data Analysis'],
      category: 'ai',
      liveUrl: 'https://calcostpro.com',
      liveUrlLabel: 'Launch calcostpro.com',
      features: [
        'Automated direct cost and bill of materials calculation',
        'Predictive margin simulator with recommended wholesale/retail prices',
        'Gemini AI assistance for profitability audits and variance detection',
        'Detailed quotation generation and technical sheet exports',
      ],
    },
    {
      id: 10,
      title: 'Chocolate Bar Packaging',
      description: 'Packaging design for a new brand of artisanal chocolate with spirulina.',
      imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
      featuredImageUrl: '/portfolio/p10-1.jpg',
      imageHints: ['chocolate packaging', 'spirulina design', 'product wrapping'],
      tags: ['Packaging', 'Product Design', 'Chocolate', 'Branding'],
      category: 'design',
    },
    {
      id: 11,
      title: 'CFAB | French Business Circle in Bolivia',
      description: 'Institutional web platform for the Cercle Français d\'Affaires en Bolivie, connecting corporate executives, investors, and bilateral trade leaders.',
      longDescription: 'The Cercle Français d\'Affaires en Bolivie (CFAB) brings together French and Bolivian business leaders, entrepreneurs, and institutions to foster bilateral economic growth.\n\nThis web project delivered an elegant, corporate platform highlighting sector commissions (energy, mining, agribusiness, services), publishing business opportunities, and offering an online directory alongside seamless membership onboarding.\n\nKey emphasis was placed on high-speed performance, clean editorial typography, and full mobile responsiveness for corporate executives.',
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg', '/portfolio/p11-3.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['cfab corporate portal', 'commissions and news page', 'membership and directory'],
      tags: ['Web Development', 'Corporate Website', 'Business Network', 'UI/UX'],
      category: 'dev',
      liveUrl: 'https://cfab.iung.li',
      liveUrlLabel: 'Visit cfab.iung.li',
      features: [
        'High-performance web architecture with instantaneous page transitions',
        'Showcase for industry commissions and economic news publications',
        'Institutional directory highlighting diplomatic and chamber partners',
        'Streamlined membership applications and qualified business inquiries',
        'SEO-optimized and 100% responsive interface crafted for business leaders',
      ],
    },
    {
      id: 12,
      title: 'Intikuna Corporate Showcase',
      description: 'Showcase website for Intikuna: refined brand identity, service highlighting, and an engaging responsive user experience.',
      longDescription: 'Intikuna is a consulting and strategic services firm advising businesses and institutions.\n\nThe development objective was to create a commanding digital presence that instills trust and highlights the firm\'s core capabilities. The site structures consulting offerings with clarity, guiding visitors toward direct inquiry and partnership opportunities.\n\nSpecial attention was dedicated to page load performance, subtle micro-interactions, and flawless mobile rendering across all devices.',
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['intikuna showcase website', 'consulting services catalog'],
      tags: ['Web Development', 'Showcase Website', 'Consulting', 'Responsive Design'],
      category: 'dev',
      liveUrl: 'https://intikuna.vercel.app/',
      liveUrlLabel: 'Visit intikuna.vercel.app',
      features: [
        'Bespoke visual design reflecting the firm\'s rigor and strategic expertise',
        'Structured service breakdown and clear corporate value propositions',
        'Frictionless conversion flow with direct contact and lead capture',
        'Ultra-fast loading speed and modern lightweight web standards',
        'Cross-device compatibility with touch-optimized mobile navigation',
      ],
    },
    {
      id: 13,
      title: 'Assofoot Sports League & Portal',
      description: 'End-to-end sports management web platform for Assofoot: league tournaments, live fixture schedules, club rosters, and real-time standings.',
      longDescription: 'Assofoot organizes and manages regional football tournaments involving numerous sports clubs, referees, and enthusiastic fan communities. Moving beyond legacy spreadsheets, the association required a centralized real-time web portal.\n\nThe custom web application features dynamic tournament divisions, a live fixture schedule with date/pitch filtering, team rosters with player bios and jersey numbers, and automated standings calculated instantly after every match day.\n\nIt also includes instant WhatsApp match sheet sharing to dispatch schedules and updates to team captains with a single tap.',
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg', '/portfolio/p13-3.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['assofoot sports portal home', 'live match fixture schedule', 'team rosters and league standings'],
      tags: ['Web Development', 'Sports Platform', 'Real-Time', 'Mobile Web', 'PWA'],
      category: 'dev',
      liveUrl: 'https://assofoot.iung.li',
      liveUrlLabel: 'Visit assofoot.iung.li',
      features: [
        'Dynamic tournament and division management across multiple sport categories',
        'Live match schedule with quick filters by date, pitch, and game status',
        'Team rosters and player directory with numbers, positions, and photos',
        'Automated league standings and tournament statistics updated post-game',
        'One-tap match sheet generation and instant sharing on WhatsApp',
        'Mobile-first responsive interface tailored for pitch-side sideline use',
      ],
    },
    /*
    {
      id: 11,
      title: 'Project 11',
      description: 'Description for project 11. Replace with your project description.',
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 12,
      title: 'Project 12',
      description: 'Description for project 12. Replace with your project description.',
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 13,
      title: 'Project 13',
      description: 'Description for project 13. Replace with your project description.',
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 14,
      title: 'Project 14',
      description: 'Description for project 14. Replace with your project description.',
      imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
      featuredImageUrl: '/portfolio/p14-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 15,
      title: 'Project 15',
      description: 'Description for project 15. Replace with your project description.',
      imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
      featuredImageUrl: '/portfolio/p15-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 16,
      title: 'Project 16',
      description: 'Description for project 16. Replace with your project description.',
      imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
      featuredImageUrl: '/portfolio/p16-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 17,
      title: 'Project 17',
      description: 'Description for project 17. Replace with your project description.',
      imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
      featuredImageUrl: '/portfolio/p17-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'design',
    },
    {
      id: 18,
      title: 'Project 18',
      description: 'Description for project 18. Replace with your project description.',
      imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
      featuredImageUrl: '/portfolio/p18-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    {
      id: 19,
      title: 'Project 19',
      description: 'Description for project 19. Replace with your project description.',
      imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
      featuredImageUrl: '/portfolio/p19-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'ai',
    },
    {
      id: 20,
      title: 'Project 20',
      description: 'Description for project 20. Replace with your project description.',
      imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
      featuredImageUrl: '/portfolio/p20-1.jpg',
      imageHints: ['project preview', 'project detail'],
      tags: ['Tag 1', 'Tag 2', 'Tag 3'],
      category: 'dev',
    },
    */
  ],
  es: [
    {
      id: 1,
      title: 'Branding para "NOE"',
      description: "Creación de una identidad visual completa para una firma de contabilidad, incluyendo logo y manual de marca.",
      imageUrls: ['/portfolio/p1-1.jpg', '/portfolio/p1-2.jpg'],
      featuredImageUrl: '/portfolio/p1-1.jpg',
      imageHints: ['diseño de logo', 'branding corporativo'],
      tags: ['Branding', 'Logo', 'Identidad Visual'],
      category: 'design',
    },
    {
      id: 2,
      title: 'Folleto de proyecto arquitectónico',
      description: "Realización de un folleto de presentación para una licitación de proyecto de arquitectura.",
      imageUrls: ['/portfolio/p2-1.jpg', '/portfolio/p2-2.jpg', '/portfolio/p2-3.jpg', '/portfolio/p2-4.jpg', '/portfolio/p2-5.jpg', '/portfolio/p2-6.jpg', '/portfolio/p2-7.jpg'],
      featuredImageUrl: '/portfolio/p2-1.jpg',
      imageHints: ['maquetación de folleto', 'diseño editorial', 'impresión arquitectura', 'folleto profesional', 'folleto moderno', 'diseño limpio', 'presentación corporativa'],
      tags: ['Edición', 'Folleto', 'Maquetación', 'Arquitectura'],
      category: 'design',
    },
    {
      id: 3,
      title: 'Packaging "Life Essential"',
      description: "Creación de una gama de packaging para una marca que elabora aceites esenciales.",
      imageUrls: ['/portfolio/p3-1.jpg'],
      featuredImageUrl: '/portfolio/p3-1.jpg',
      imageHints: ['packaging de producto', 'branding de cosméticos'],
      tags: ['Packaging', 'Diseño de Producto', 'Aceites Esenciales'],
      category: 'design',
    },
    {
      id: 4,
      title: 'Identidad visual "SABSA"',
      description: "Creacion de una identidad visual por los aeropuertos de Bolivia con un aplicacion en todo tipo de soportes",
      imageUrls: ['/portfolio/p4-1.jpg', '/portfolio/p4-2.jpg', '/portfolio/p4-3.jpg', '/portfolio/p4-4.jpg', '/portfolio/p4-5.jpg'],
      featuredImageUrl: '/portfolio/p4-1.jpg',
      imageHints: ['diseño de póster', 'campaña social', 'conciencia gráfica', 'arte ambiental', 'tipografía audaz'],
      tags: ['Identidad Visual', 'Dirección de Arte', 'Campaña Social'],
      category: 'design',
    },
    {
      id: 5,
      title: 'Logo "Chichi Pizza"',
      description: "Creación de una identidad visual completa para una nueva empresa de reparto a domicilio, incluyendo logo, manual de marca y soportes de marketing.",
      imageUrls: ['/portfolio/p5-1.jpg', '/portfolio/p5-2.jpg', '/portfolio/p5-3.jpg', '/portfolio/p5-4.jpg', '/portfolio/p5-5.jpg'],
      featuredImageUrl: '/portfolio/p5-1.jpg',
      imageHints: ['pizza logo', 'branding de alimentos', 'identidad de restaurante', 'diseño para llevar', 'logo moderno'],
      tags: ['Logo', 'Branding', 'Restauración', 'Marketing'],
      category: 'design',
    },
    {
      id: 6,
      title: 'Boutique en línea Loampsi',
      description: 'Diseño y desarrollo de una plataforma e-commerce de moda para venta de accesorios y creaciones exclusivas.',
      longDescription: 'Loampsi es una boutique en línea especializada en accesorios de moda y confecciones artesanales.\n\nEl proyecto consistió en desarrollar una tienda e-commerce ágil, elegante y completamente responsive, integrando catálogo con variantes, pasarelas de pago seguras y un panel de administración para control de pedidos e inventario.',
      imageUrls: ['/portfolio/p6-1.jpg', '/portfolio/p6-2.jpg'],
      featuredImageUrl: '/portfolio/p6-1.jpg',
      imageHints: ['boutique moda', 'comercio electrónico', 'diseño web'],
      tags: ['Desarrollo Web', 'E-commerce', 'WooCommerce', 'UI/UX'],
      category: 'dev',
      liveUrl: 'https://loampsi.com',
      liveUrlLabel: 'Visitar loampsi.com',
      features: [
        'Tienda online completa con WordPress y WooCommerce',
        'Catálogo de productos con fotografía en alta resolución y variantes',
        'Proceso de compra intuitivo y pasarelas de pago protegidas',
        'Panel de gestión ágil para control de existencias y pedidos',
      ],
    },
    {
      id: 7,
      title: 'Bisutería',
      description: "Aplicación web que genera paletas de colores y sugerencias de fuentes basadas en un concepto, usando IA.",
      imageUrls: ['/portfolio/p7-1.jpg', '/portfolio/p7-2.jpg'],
      featuredImageUrl: '/portfolio/p7-1.jpg',
      imageHints: ['herramienta ia', 'paleta de colores'],
      tags: ['IA', 'Herramienta de Diseño', 'Genkit', 'Creatividad'],
      category: 'design',
    },
    {
      id: 8,
      title: 'Sitio de consultacion en linea',
      description: 'Desarrollo de un sitio de comercio electrónico completo con WordPress y WooCommerce, incluyendo personalización del tema e integración de plugins.',
      imageUrls: ['/portfolio/p8-1.jpg', '/portfolio/p8-2.jpg', '/portfolio/p8-3.jpg', '/portfolio/p8-4.jpg'],
      featuredImageUrl: '/portfolio/p8-1.jpg',
      imageHints: ['tienda ecommerce', 'página de producto', 'tienda online', 'sitio web de moda'],
      tags: ['Desarrollo Web', 'WordPress', 'E-commerce', 'WooCommerce'],
      category: 'dev',
    },
    {
      id: 9,
      title: 'CalCostPro - Aplicación Web con IA',
      description: 'Desarrollo de CalCostPro (calcostpro.com), aplicación SaaS con IA para el cálculo preciso de costos y precios de venta en la confección textil.',
      longDescription: 'CalCostPro es una aplicación SaaS de ingeniería financiera desarrollada para la industria de la confección y la moda. Permite desglosar detalladamente el costo unitario de cada prenda (telas, insumos, mano de obra, tiempos de patronaje, mermas) y aprovecha modelos de IA (Gemini) para sugerir precios de venta óptimos y detectar desviaciones de rentabilidad.',
      imageUrls: ['/portfolio/p9-1.jpg', '/portfolio/p9-2.jpg', '/portfolio/p9-3.jpg', '/portfolio/p9-4.jpg', '/portfolio/p9-5.jpg', '/portfolio/p9-6.jpg'],
      featuredImageUrl: '/portfolio/p9-1.jpg',
      imageHints: ['dashboard app', 'financial analysis', 'pricing tool', 'ai application', 'ui design', 'ux saas'],
      tags: ['Desarrollo Web', 'IA', 'SaaS', 'Firebase', 'Next.js', 'Análisis de Datos'],
      category: 'ai',
      liveUrl: 'https://calcostpro.com',
      liveUrlLabel: 'Abrir calcostpro.com',
      features: [
        'Cálculo automatizado de costos directos y consumos de materiales',
        'Simulador predictivo de márgenes y sugerencias de precios comerciales',
        'Asistente IA (Gemini) para auditoría de rentabilidad y alertas de sobrecosto',
        'Generación de cotizaciones profesionales y fichas técnicas exportables',
      ],
    },
    {
      id: 10,
      title: 'Packaging de tableta de chocolate',
      description: 'Diseño de packaging para una nueva marca de chocolate artesanal con espirulina.',
      imageUrls: ['/portfolio/p10-1.jpg', '/portfolio/p10-2.jpg', '/portfolio/p10-3.jpg'],
      featuredImageUrl: '/portfolio/p10-1.jpg',
      imageHints: ['packaging de chocolate', 'diseño espirulina', 'envoltura de producto'],
      tags: ['Packaging', 'Diseño de Producto', 'Chocolate', 'Branding'],
      category: 'design',
    },
    {
      id: 11,
      title: 'CFAB | Círculo Francés de Negocios en Bolivia',
      description: 'Diseño y desarrollo de la plataforma web institucional para el Círculo Francés de Negocios en Bolivia, red bilateral que une a empresarios, inversionistas y expertos.',
      longDescription: 'El Círculo Francés de Negocios en Bolivia (CFAB) congrega a empresas, emprendedores y actores económicos bilaterales entre Francia y Bolivia.\n\nEl proyecto web tuvo como meta estructurar un portal institucional de primer nivel: visibilidad de comisiones sectoriales (energía, minería, agroindustria, servicios), difusión de oportunidades comerciales, directorio corporativo y gestión digital de afiliaciones.\n\nSe priorizó una experiencia de usuario distinguida, velocidad de carga instantánea, tipografía sobria y óptima adaptación a dispositivos móviles para ejecutivos y líderes empresariales.',
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg', '/portfolio/p11-3.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['sitio institucional cfab', 'página comisiones y noticias', 'afiliaciones y directorio'],
      tags: ['Desarrollo Web', 'Sitio Institucional', 'Red de Negocios', 'UI/UX'],
      category: 'dev',
      liveUrl: 'https://cfab.iung.li',
      liveUrlLabel: 'Visitar cfab.iung.li',
      features: [
        'Arquitectura web moderna con navegación fluida y sin recargas pesadas',
        'Módulos para comisiones de trabajo y publicaciones económicas',
        'Espacio dedicado a socios institucionales y enlaces diplomáticos',
        'Formularios de membresía y consultas comerciales cualificadas',
        'Optimización SEO y diseño 100% responsive para directivos y tomadores de decisiones',
      ],
    },
    {
      id: 12,
      title: 'Sitio web corporativo Intikuna',
      description: 'Desarrollo de sitio web corporativo para Intikuna: identidad visual sobria, presentación de servicios estratégicos y navegación responsive de alta fidelidad.',
      longDescription: 'Intikuna es una consultora especializada en asesoramiento estratégico y servicios profesionales de alto impacto.\n\nEl proyecto consistió en construir una presencia digital sólida que transmita credibilidad ante clientes y aliados. El sitio organiza las áreas de asesoramiento de forma didáctica y orienta al visitante hacia un contacto comercial directo y efectivo.\n\nSe dedicó especial atención a la rapidez de carga, a las microinteracciones y a una lectura impecable en todo tipo de pantallas móviles.',
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['sitio corporativo intikuna', 'catálogo de servicios estratégicos'],
      tags: ['Desarrollo Web', 'Sitio Corporativo', 'Consultoría', 'Diseño Responsive'],
      category: 'dev',
      liveUrl: 'https://intikuna.vercel.app/',
      liveUrlLabel: 'Visitar intikuna.vercel.app',
      features: [
        'Diseño a medida que refleja el rigor y la solidez de la firma',
        'Estructura editorial clara con desglose de servicios y metodologías',
        'Canal de conversión directo mediante formularios de contacto',
        'Rendimiento web optimizado con tiempos de respuesta instantáneos',
        'Compatibilidad multiplataforma y ergonomía táctil en smartphones y tablets',
      ],
    },
    {
      id: 13,
      title: 'Portal y Gestión Deportiva Assofoot',
      description: 'Desarrollo integral de una aplicación web para la gestión deportiva de Assofoot: fixtures de torneos, calendario de partidos en vivo, plantillas y resultados.',
      longDescription: 'Assofoot organiza y administra campeonatos de fútbol que reúnen a decenas de clubes, árbitros y aficionados. Superando la gestión dispersa en planillas manuales, se implementó una plataforma digital centralizada en tiempo real.\n\nLa aplicación permite la administración de categorías y torneos, calendario interactivo de encuentros (fechas, horarios, canchas), registro detallado de clubes y jugadores (fotos, dorsales, posiciones) y actualización inmediata de tablas de posiciones.\n\nIncluye además un módulo de difusión directa vía WhatsApp para compartir fichas de partidos y convocatorias con capitanes e hinchas en un solo clic.',
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg', '/portfolio/p13-3.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['portal deportivo assofoot inicio', 'calendario de partidos en vivo', 'fichas de equipos y tablas'],
      tags: ['Desarrollo Web', 'Deportes', 'Aplicación Web', 'Tiempo Real', 'PWA'],
      category: 'dev',
      liveUrl: 'https://assofoot.iung.li',
      liveUrlLabel: 'Visitar assofoot.iung.li',
      features: [
        'Gestión dinámica de torneos, series y temporadas deportivas',
        'Calendario de partidos en tiempo real con filtros por cancha y estado',
        'Fichas de equipos y catálogo de futbolistas con fotos y dorsales',
        'Tablas de posiciones y estadísticas calculadas de forma automatizada',
        'Generación y envío instantáneo de hojas de partido por WhatsApp',
        'Interfaz pensada mobile-first para consulta rápida desde el campo de juego',
      ],
    },
    /*
    {
      id: 11,
      title: 'Proyecto 11',
      description: 'Descripción del proyecto 11. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p11-1.jpg', '/portfolio/p11-2.jpg'],
      featuredImageUrl: '/portfolio/p11-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'design',
    },
    {
      id: 12,
      title: 'Proyecto 12',
      description: 'Descripción del proyecto 12. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p12-1.jpg', '/portfolio/p12-2.jpg'],
      featuredImageUrl: '/portfolio/p12-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'dev',
    },
    {
      id: 13,
      title: 'Proyecto 13',
      description: 'Descripción del proyecto 13. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p13-1.jpg', '/portfolio/p13-2.jpg'],
      featuredImageUrl: '/portfolio/p13-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'ai',
    },
    {
      id: 14,
      title: 'Proyecto 14',
      description: 'Descripción del proyecto 14. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p14-1.jpg', '/portfolio/p14-2.jpg'],
      featuredImageUrl: '/portfolio/p14-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'design',
    },
    {
      id: 15,
      title: 'Proyecto 15',
      description: 'Descripción del proyecto 15. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p15-1.jpg', '/portfolio/p15-2.jpg'],
      featuredImageUrl: '/portfolio/p15-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'dev',
    },
    {
      id: 16,
      title: 'Proyecto 16',
      description: 'Descripción del proyecto 16. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p16-1.jpg', '/portfolio/p16-2.jpg'],
      featuredImageUrl: '/portfolio/p16-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'ai',
    },
    {
      id: 17,
      title: 'Proyecto 17',
      description: 'Descripción del proyecto 17. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p17-1.jpg', '/portfolio/p17-2.jpg'],
      featuredImageUrl: '/portfolio/p17-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'design',
    },
    {
      id: 18,
      title: 'Proyecto 18',
      description: 'Descripción del proyecto 18. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p18-1.jpg', '/portfolio/p18-2.jpg'],
      featuredImageUrl: '/portfolio/p18-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'dev',
    },
    {
      id: 19,
      title: 'Proyecto 19',
      description: 'Descripción del proyecto 19. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p19-1.jpg', '/portfolio/p19-2.jpg'],
      featuredImageUrl: '/portfolio/p19-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'ai',
    },
    {
      id: 20,
      title: 'Proyecto 20',
      description: 'Descripción del proyecto 20. Reemplazar con la descripción de su proyecto.',
      imageUrls: ['/portfolio/p20-1.jpg', '/portfolio/p20-2.jpg'],
      featuredImageUrl: '/portfolio/p20-1.jpg',
      imageHints: ['vista previa proyecto', 'detalle proyecto'],
      tags: ['Etiqueta 1', 'Etiqueta 2', 'Etiqueta 3'],
      category: 'dev',
    },
    */
  ],
};




